### ISSUE TITLE
TBC Classic plan

### ISSUE THREAD

**Issue by Macumbafeh** [BigWigsMods/Capping#102]
Hello !

I liked your addon for classic. I want to know if you plan to port it to tbc classic?

Thanks :)

**Comment by xathian** [comment]
Yeah needs fixing, AV timers are all off now

**Comment by dok1100** [comment]
I join the request... :)

@xathian 
1. open "AlteracValley.lua" in "Modules" folder 
2. go to line 167 or search "self:StartFlagCaptures(300, 1459)" without "
3. change the 300 to 240 (that is the duration of the timer in seconds) I have 245 because it always takes 5 seconds longer

**Comment by funkydude** [comment]
Update is out.
