### ISSUE TITLE
unable to configure the addon on the TBC classic client

### ISSUE THREAD

**Issue by octapusxft** [BigWigsMods/Capping#103]
## Describe the problem
I cannot open the options of the addon. It gives no error or anything, it just that nothing happens

### What steps will reproduce the problem?

1.  attempt to open options with /capping

### What version of the addon are you using? (Stating 'latest' is not useful)
v9.0.16

### Do you have an error log of what happened?
nope, no error nothing shown

### Any additional information? (example: WoW language if not English)
English language

**Comment by funkydude** [comment]
Sounds like you didn't have load out of date addons enabled. It's updated now regardless.
