### ISSUE TITLE
Add Health Tracking for Mini-Bosses and Bosses in Ashran Epic Battleground?

### ISSUE THREAD

**Issue by codetwink** [BigWigsMods/Capping#108]
## Describe the problem
Currently it does not track the bosses or mini-bosses health, like it does for Drek, Van, Ice Lord and Tree in Alterac Valley.

### What steps will reproduce the problem?

1.  Get into an Ashran Epic Battleground.
2.  Farm enough fragments to summon Kronus or Fangraal.
3.  Enemy team engages with your mini-boss and capping shows no health meters.

### What version of the addon are you using? (Stating 'latest' is not useful)
9.1.0

### Do you have an error log of what happened?
Not really an error, more like a feature to be added.

### Any additional information? (example: WoW language if not English)

Here are the wowhead links for the bosses and mini-bosses that you could probably just add the one line per entry into the Ashran.lua script to support their health meters.

Bosses:
-Grand Marshall Tremblade
--https://www.wowhead.com/npc=82876/grand-marshal-tremblade
-High Warlord Volrath
--https://www.wowhead.com/npc=82877/high-warlord-volrath

Mini-Bosses:
-Fangraal
--https://www.wowhead.com/npc=81859/fangraal
-Kronus
--https://www.wowhead.com/npc=82201/kronus

**Comment by funkydude** [comment]
Added in latest release.
