### ISSUE TITLE
bg timer inoccurate

### ISSUE THREAD

**Issue by Macumbatbc** [BigWigsMods/Capping#111]
Hello,

I tried the addon, and timers are not occurate. i tested it in Arathi and Alterac.

Thanks.

**Comment by Macumbatbc** [comment]
i tried with /chrono on a base, the addon is set to 59 sec and we get a base at 1:05 min

**Comment by funkydude** [comment]
Closing as BCC is over, if it's still an issue on Wrath please open a new issue.

**Comment by Macumbatbc** [comment]
Thanks anyway, i made my change and the addon was perfect.
I need to test on wotlk but it seems some towers aren't tracked in Alterac.

**Comment by funkydude** [comment]
There's no where in the addon which could enable it to only track specific towers and exclude others. Please open a new issue with full details on what is happening including screenshots.

**Comment by Macumbatbc** [comment]
I mean sometimes it track it, sometimes not.
I'll do more test anyway.
