### ISSUE TITLE
minor issue: obsolete info text

### ISSUE THREAD

**Issue by ghost** [BigWigsMods/Capping#112]
Hey Funkelz, great addon! Thanks for that :)

Each time I load into the game (or reloadUI) I am getting that little help text that localization issue for the German version is needed (might be true for different language clients as well) even though by now you have a solid German localization shipped.

Can we please get rid of that text? Many thanks!

![image](https://user-images.githubusercontent.com/16833/173885192-58a28390-7c6d-40d8-8310-5264a122018f.png)

**Comment by funkydude** [comment]
German is not fully translated, the message will stay until someone finishes the translations.
