### ISSUE TITLE
Capping locale for ES_ES reported as non existent in the game

### ISSUE THREAD

**Issue by moonloop00** [BigWigsMods/Capping#113]
## Describe the problem
Capping locale for ES_ES reported as non existent in the game

### What steps will reproduce the problem?
1. Just start the game

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![capping](https://user-images.githubusercontent.com/103313456/186971716-f625c95f-cd79-41fa-9553-bdaede549951.png)

### Do you have an error log of what happened?
NA

### Any additional information? (example: WoW language if not English)
WoW language is ES ES

**Comment by moonloop00** [comment]
The locale appears as commented https://github.com/BigWigsMods/Capping/blob/master/Locales/esES.lua

**Comment by funkydude** [comment]
Correct, it is commented i.e. not translated, so the message will remain until someone does this. The addon cannot fully function without all translations as it relies on exact copies of the text of in-game NPC yells to start certain timers.

**Comment by moonloop00** [comment]
I would gladly add a translation

Which is a full translation I can use to check what are the expected messages and its variable names? Is this one complete? https://github.com/BigWigsMods/Capping/blob/master/Locales/ptBR.lua

Thanks

**Comment by funkydude** [comment]
What do you mean? Just look at the English (enUS) one?
