### ISSUE TITLE
Bug with timers in Alterac

### ISSUE THREAD

**Issue by Macumbafeh** [BigWigsMods/Capping#116]
Hello !

Me again :)

I tested more the addon for wotlk, so first of all, i have a french client, and the issue is in Alterac.

The Mines seems to be tracked well but not the tower and GY, i have no timers when someone take them. enemy or ally.
![image](https://user-images.githubusercontent.com/47739411/188518133-c0c5cd82-0283-4796-83b3-51c21628c7fe.png)

What is interesting also, it's when someone take back a tower, then the timer start ! like if the timer's trigger was reversed.

As you can see here the horde takes the GY back and then the timer started
![image](https://user-images.githubusercontent.com/47739411/188518370-8a3b44f8-27c6-4903-9c6c-449e6d7d9b9d.png)

Same think here with the ally's tower which they takes back
![image](https://user-images.githubusercontent.com/47739411/188518541-cc7fd3cb-7a88-403f-97ee-9141f51e7481.png)

I tested Arathi just after and it's all good 👍 !

**Comment by funkydude** [comment]
The only way I see this happening is if the order of the textures was different in the French client which would be super weird. I'll change my client to French and test it myself.

**Comment by Macumbafeh** [comment]
it was working perfect in TBC that's strange : /

**Comment by funkydude** [comment]
I just tested in French and it works fine. You're obviously using an old version. Please use the Curseforge app to keep your addons up to date to avoid such issues.

Also in future please answer the questions that are asked of you when creating a new issue, like telling us what version you are using.

**Comment by Macumbatbc** [comment]
Yes, i just saw it... I'm a noob 
I didn't updated the addon.
Sorry for that. Ty anyway
