### ISSUE TITLE
Queue Timers being shown altho setting disabled

### ISSUE THREAD

**Issue by kealsera** [BigWigsMods/Capping#118]
## Describe the problem
Queue Timers will be hidden once you uncheck the checkbox. However on reload/restart the queue timers will still be shown - the checkbox for queue timer is unchecked. It seems the setting is not enforced on reload?

### What steps will reproduce the problem?

1.  Install Addon
2.  Disable Queue Timers
3.  Reload/Restart WoW

### What version of the addon are you using? (Stating 'latest' is not useful)
9.2.4

**Comment by funkydude** [comment]
Cannot reproduce this, working fine here. You're probably confusing queue bars for battleground entrance timers. The entrance timers cannot be disabled, they are a separate feature.

**Comment by kealsera** [comment]
Thats weird tho as these Battleground Entrance Timers are hidden as soon as I uncheck the Queue Checkbox? But k, its not that important :)
