### ISSUE TITLE
Green border and title showing at all times even when not in a BG

### ISSUE THREAD

**Issue by secphish** [BigWigsMods/Capping#119]
## Describe the problem
Green border and title for the addon both in and out of a BG.
Not sure if this is normal behavior or if there's a setting I need to change to have the green border and title gone.
![image](https://user-images.githubusercontent.com/90019011/190301159-04d638bc-7595-4193-85b1-e77bc306df3a.png)

![image](https://user-images.githubusercontent.com/90019011/190302453-f7296d3a-b8bd-4631-a131-b1c7b668bc2d.png)

### What steps will reproduce the problem?

1.  Installed the addon
2. Have the same issue on Retail too

### What version of the addon are you using? (Stating 'latest' is not useful)
3.4.0 Version

### Do you have an error log of what happened?
No

### Any additional information? (example: WoW language if not English)
No

**Comment by funkydude** [comment]
Yes it's normal. Open the UI options by typing `/capping` and lock it.
