### ISSUE TITLE
Feature Request: Configurable bar clicks

### ISSUE THREAD

**Issue by cgreczkowski** [BigWigsMods/Capping#12]
It would be nice to shift+click and link to whichever chat the player has selected.

Auto send should also be disabled.

**Comment by IPS277L** [comment]
You can do it using ctrl + click
```lua
function BarOnClick(bar)
    if IsShiftKeyDown() then
        ReportBar(bar, "SAY")
    elseif IsControlKeyDown() then
        ReportBar(bar, IsInGroup(2) and "INSTANCE_CHAT" or "RAID")
```
But it would be nice if author will add settings for this
