### ISSUE TITLE
Timer of winning in Arathi Basin is not working

### ISSUE THREAD

**Issue by sheha316** [BigWigsMods/Capping#122]
## Describe the problem
There was a timer in Arathi Basin that tells you when the game will end, with a estimated time and Resource points for each team.

### What steps will reproduce the problem?

1.  Queue for Alterac Valley
2.  Wait until a base is captured 
3.  You will not see the timer

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)

![image](https://user-images.githubusercontent.com/26840117/190863490-42845414-e631-4417-af11-f335ffd7f171.png)
![image](https://user-images.githubusercontent.com/26840117/190863703-d05068d3-7c79-494c-a384-636d72e9cdcd.png)

### What version of the addon are you using? (Stating 'latest' is not useful)
3.4.0

### Do you have an error log of what happened?
No

### Any additional information? (example: WoW language if not English)
No

**Comment by sheha316** [comment]
hi, i think that i didn't put the rigth version of the addon, here it is: Capping-v9.2.5.zip

**Comment by funkydude** [comment]
Thanks, will be fixed in the next release.
