### ISSUE TITLE
Addon doesn't work in Dragonflight pre-patch for retail/live

### ISSUE THREAD

**Issue by pavenarius** [BigWigsMods/Capping#125]
## Describe the problem
None of the battleground timers seem to work in the latest Dragonflight pre-patch version of the game.

### What steps will reproduce the problem?

1.  Enter any battleground
2.  Note that during play none of the bars are triggered based on various battleground events (capping flags or forts, etc).

### What version of the addon are you using? (Stating 'latest' is not useful)
10.0.0

### Do you have an error log of what happened?
No LUA errors are thrown that I can see

**Comment by funkydude** [comment]
Thanks!

**Comment by pavenarius** [comment]
Wow, thank you for the quick turnaround!

**Comment by funkydude** [comment]
> Wow, thank you for the quick turnaround!

No problem. I would highly recommend installing the BugSack addon to grab Lua errors, it is very helpful when reporting issues to addon devs. There were multiple errors but you said there were none, so I'm just assuming you don't have it installed.
