### ISSUE TITLE
Korrak's Revenge issue

### ISSUE THREAD

**Issue by DefectiveTank** [BigWigsMods/Capping#126]
The latest retail version does not work the anniversary event Korrak's Revenge which is a modified version of Alterac Valley.  What is funny is if I downgrade and go back to version 10.0.1 from October 27 I get all the timers working.  I assume since Korrak's Revenge is a yearly event that support is desired.  People have discussed it in the chat in the BG.

### What steps will reproduce the problem?

1.  Download latest version of Capping.
2.  Queue up for Korrak's Revenge.
3.  

### What version of the addon are you using? (Stating 'latest' is not useful)
v10.0.3

**Comment by funkydude** [comment]
This was removed under the (wrong) assumption that it was no longer in the game. It's now restored in the latest release.
