### ISSUE TITLE
Korrak's Revenge: "New id found, tell the devs"

### ISSUE THREAD

**Issue by linaori** [BigWigsMods/Capping#127]
## Describe the problem
When I'm talking to the alliance np to hand in the armor scraps quest I get this:
```
1x Capping: NEW ID FOUND, TELL THE DEVS! 30904, 13257, Upgrade to seasoned units!
[string "@Interface/AddOns/Capping/Core.lua"]:189: in function <Interface/AddOns/Capping/Core.lua:184>
```

NPC is Murgot Deepforge. It only triggers for the blue quest, not the yellow daily.

### What steps will reproduce the problem?

1.  Complete yellow armor scraps quest
2.  Talk to NPC again to hand in the blue version

Version: 10.0.4

**Comment by funkydude** [comment]
Thanks for letting us know!
