### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by Somatics23** [BigWigsMods/Capping#128]
## Describe the problem
i got a lua error 

### What steps will reproduce the problem?

1.  when people capped bases in AB
2.  
3.  

### What version of the addon are you using? (Stating 'latest' is not useful)
10.0.10

### Do you have an error log of what happened?
Message: Interface/AddOns/Capping/Core_Wrath.lua:640: attempt to call upvalue 'GetPOITextureCoords' (a nil value)
Time: Mon Jan 23 13:43:17 2023
Count: 2
Stack: Interface/AddOns/Capping/Core_Wrath.lua:640: attempt to call upvalue 'GetPOITextureCoords' (a nil value)
[string "@Interface/AddOns/Capping/Core_Wrath.lua"]:640: in function <Interface/AddOns/Capping/Core_Wrath.lua:639>
[string "@Interface/AddOns/Capping/Core_Wrath.lua"]:657: in function `v'
[string "@Interface/AddOns/Capping/Core_Wrath.lua"]:187: in function <Interface/AddOns/Capping/Core_Wrath.lua:184>

Locals: icon = 34
(*temporary) = <table> {
 1 = 136441
}
(*temporary) = <table> {
 1 = 136441
}
(*temporary) = <table> {
 1 = 136441
}
(*temporary) = <table> {
 1 = 136441
}
(*temporary) = nil
(*temporary) = 34
(*temporary) = "attempt to call upvalue 'GetPOITextureCoords' (a nil value)"
path = <table> {
 1 = 136441
}
GetPOITextureCoords = nil

**Comment by funkydude** [comment]
Thanks for reporting this, a fix is in the latest version now.

**Comment by Somatics23** [comment]
no problem, thank you!
