### ISSUE TITLE
LUA error in Alterac Valley

### ISSUE THREAD

**Issue by tomten2k4** [BigWigsMods/Capping#129]
## Describe the problem

LUA error when joining a raid in AV

### What steps will reproduce the problem?

1.   Joining AV

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![bild](https://user-images.githubusercontent.com/123874362/215326304-e1872a47-b801-4b27-9f7e-bc33ec5eddac.png)

### What version of the addon are you using? (Stating 'latest' is not useful)
10.0.12

**Comment by funkydude** [comment]
Thanks for reporting this. I don't understand how this error was caused but hopefully it shouldn't happen again.
