### ISSUE TITLE
Feature Request: Enable/Disable Specific Bars

### ISSUE THREAD

**Issue by eli-j-s** [BigWigsMods/Capping#132]
I don't want the queue bars or the arena time remaining bars, I already have addons that do this and the default ui shows time left for the arena.  I deleted the queue.lua files, but I do not know how to edit the arena.lua file to only show the shadow sight bar.  An option to select what bars we need and don't need instead of deleting the entire module would be great!!

**Comment by funkydude** [comment]
The queue timers already have the ability to be disabled. More fine grained options for specific zones will come some time in future.
