### ISSUE TITLE
Not seeing time remaining text at the top of the screen

### ISSUE THREAD

**Issue by stevengrimaldo** [BigWigsMods/Capping#133]
## Describe the problem
Not seeing the timer countdown at the top of the screen underneath the icons as i see in other peoples streams/vods.

I normally would have seen the time remaining in the color of the winning team but i do not see that.

### What steps will reproduce the problem?

1.  installed addon
2.  queued for Arathi Basin, The Battle for Gilneas, Eye of the Storm
3.  did not see the timer at the top under the icons,

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![Screenshot 2023-05-23 155904](https://github.com/BigWigsMods/Capping/assets/3181158/d3cdf9f6-c35c-41b2-84ba-c69d971770e0)

### What version of the addon are you using? (Stating 'latest' is not useful)
Capping-v10.1.0.zip (just downloaded it right now again 4:00pm 5/23/2023 on curseforge windows app

### Do you have an error log of what happened?
no errors

### Any additional information? (example: WoW language if not English)
For reference here is what my friend is seeing:
![Screenshot 2023-05-23 161127](https://github.com/BigWigsMods/Capping/assets/3181158/6b280665-ec97-460e-8732-168e48c6f69a)

**Comment by funkydude** [comment]
You can see the time remaining as a Capping bar in the first screenshot.

The second screenshot isn't Capping. It would be pointless to add the time remaining there when it's already displayed as a bar.

**Comment by stevengrimaldo** [comment]
that's what i was thinking too but i had asked the person who had it what it was and they said capping, i then separately asked someone in a discord and they also said capping so i thought i'd try here incase 2 for 2 wasn't a coincidence
