### ISSUE TITLE
New ID

### ISSUE THREAD

**Issue by BenWagner-UX** [BigWigsMods/Capping#135]
Had to register an account here to follow your orders ;)

[11:28:34] Capping: NEW ID FOUND, **TELL THE DEVS!** 90270 13257 Upgrade to seasoned units!

Not really an issue.

**Comment by BenWagner-UX** [comment]
Happened in Alterac Valley

**Comment by funkydude** [comment]
This doesn't seem right. Were you in some kind of special version of AV?

**Comment by BenWagner-UX** [comment]
No special av as far as I know, some more information:

Game: WotlK Classic
Server: Earthshaker EU (Alliance)
Buffs: Joyous Journeys
Event: Call on Arms
Battleground: Alterac Valley
Date: Between 16. June - 18. June 2023


Thank you for your good work here =)

**Comment by furydeath9** [comment]
Same Capping: NEW ID FOUND, TELL THE DEVS! 97507 13176 How many more supplies are needed for the next upgrade?

**Comment by furydeath9** [comment]
I'm still getting, NEW ID FOUND, TELL THE DEVS! 97508 13176 How many more supplies are needed for the next upgrade? after the update but a giant box pops up now

**Comment by funkydude** [comment]
Thanks, fixed that one also

**Comment by wotlk-addon** [comment]
17x Capping: NEW ID FOUND, TELL THE DEVS! 97829, 13257, How many more supplies are needed for the next upgrade?
[string "@Capping/Core_Vanilla.lua"]:189: in function <Capping/Core_Vanilla.lua:184>
