### ISSUE TITLE
Brawl: Arathi Blizzard Spamming chat

### ISSUE THREAD

**Issue by Dimmn** [BigWigsMods/Capping#14]
When i am in the Arathi Blizzard brawl I am getting spammed in chat..

Below is the messages Im getting it doesnt stop.
![image](https://user-images.githubusercontent.com/16833/43804599-78ce528e-9a94-11e8-9c5e-111ecc048fc3.png)

**Comment by funkydude** [comment]
Can you run the following code in the battleground and tell me the results:
`/run print(GetBestMapForUnit("player"))`

**Comment by funkydude** [comment]
Fixed by 28c69c0a560b8f972b05140fabfad6a65e832b6c
