### ISSUE TITLE
No timers 

### ISSUE THREAD

**Issue by furydeath9** [BigWigsMods/Capping#141]
Bar's do not work in era the only thing it shows is start time and boss HP

**Comment by funkydude** [comment]
I assume you're talking about in Alterac Valley?
Do you have BugSack installed to grab errors?

**Comment by Wargoose** [comment]
> Had the same problem as OP, started after tuesday's reset in classic era.  went and installed bugsack - this is what I saw: 

5x Capping/Core_Vanilla.lua:650: attempt to call upvalue 'GetPOITextureCoords' (a nil value)
[string "@Capping/Core_Vanilla.lua"]:650: in function <Capping/Core_Vanilla.lua:649>
[string "@Capping/Core_Vanilla.lua"]:667: in function `v'
[string "@Capping/Core_Vanilla.lua"]:187: in function <Capping/Core_Vanilla.lua:184>

Locals:
icon = 3
(*temporary) = <table> {
 1 = 136441
}
(*temporary) = <table> {
 1 = 136441
}
(*temporary) = <table> {
 1 = 136441
}
(*temporary) = <table> {
 1 = 136441
}
(*temporary) = nil
(*temporary) = 3
(*temporary) = "attempt to call upvalue 'GetPOITextureCoords' (a nil value)"
path = <table> {
 1 = 136441
}
GetPOITextureCoords = nil


Hope that helps, Lmk if there's anything else I should be looking for that helps.

**Comment by funkydude** [comment]
Thanks @Wargoose for giving us the error, fixed.

**Comment by Wargoose** [comment]
Working great now, thanks for the update guys
