### ISSUE TITLE
NEW ID FOUND, TELL THE DEVS! 97833, 13257, Upgrade to seasoned units!

### ISSUE THREAD

**Issue by Angerreign** [BigWigsMods/Capping#143]
Happens at Classic AV, blacksmith turn-ins.

5x Capping: NEW ID FOUND, TELL THE DEVS! 97833, 13257, Upgrade to seasoned units!
[string "@Capping/Core_Vanilla.lua"]:189: in function <Capping/Core_Vanilla.lua:184>

Locals:
_ = CappingFrame {
 RearrangeBars = <function> defined @Capping/Core_Vanilla.lua:66
 header = FontString {
 }
 db = <table> {
 }
 Test = <function> defined @Capping/Core_Vanilla.lua:947
 bars = <table> {
 }
 bg = Texture {
 }
 0 = <userdata>
}
event = "GOSSIP_SHOW"
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
  = "GOSSIP_SHOW"
}
(for control) = <table> {
 GetBar = <function> defined @Capping/Core_Vanilla.lua:174
 RegisterZone = <function> defined @Capping/Core_Vanilla.lua:209
 ExitZone = <function> defined @Capping/Modules/AlteracValley_Vanilla.lua:265
 RestoreFlagCaptures = <function> defined @Capping/Core_Vanilla.lua:770
 SelectGossipID = <function> defined @Capping/Core_Vanilla.lua:799
 StartBar = <function> defined @Capping/Core_Vanilla.lua:100
 EnterZone = <function> defined @Capping/Modules/AlteracValley_Vanilla.lua:241
 StopAllBars = <function> defined @Capping/Core_Vanilla.lua:168
 GOSSIP_SHOW = <function> defined @Capping/Modules/AlteracValley_Vanilla.lua:23
 QUEST_COMPLETE = <function> defined @Capping/Modules/AlteracValley_Vanilla.lua:147
 StopScoreEstimator = <function> defined @Capping/Core_Vanilla.lua:553
 GetGossipID = <function> defined @Capping/Core_Vanilla.lua:790
 QUEST_PROGRESS = <function> defined @Capping/Modules/AlteracValley_Vanilla.lua:132
 CHAT_MSG_ADDON = <function> defined @Capping/Modules/AlteracValley_Vanilla.lua:219
 GetGossipAvailableQuestID = <function> defined @Capping/Core_Vanilla.lua:807
 RegisterEvent = <function> defined @Capping/Core_Vanilla.lua:194
 GetGossipNumOptions = <function> defined @Capping/Core_Vanilla.lua:786
 StartScoreEstimatorAB = <function> defined @Capping/Core_Vanilla.lua:541
 StartFlagCaptures = <function> defined @Capping/Core_Vanilla.lua:724
 StopFlagCaptures = <function> defined @Capping/Core_Vanilla.lua:766
 StopHealthCheck = <function> defined @Capping/Core_Vanilla.lua:373
 StartScoreEstimator = <function> defined @Capping/Core_Vanilla.lua:531
 StopBar = <function> defined @Capping/Core_Vanilla.lua:149
 Timer = <function> defined @Capping/Core_Vanilla.lua:214
 SelectGossipAvailableQuestID = <function> defined @Capping/Core_Vanilla.lua:816
 UnregisterEvent = <function> defined @Capping/Core_Vanilla.lua:199
 SetupHealthCheck = <function> defined @Capping/Core_Vanilla.lua:362
}
k = <table> {
 GetBar = <function> defined @Capping/Core_Vanilla.lua:174
 RegisterZone = <function> defined @Capping/Core_Vanilla.lua:209
 ExitZone = <function> defined @Capping/Modules/AlteracValley_Vanilla.lua:265
 RestoreFlagCaptures = <function> defined @Capping/Core_Vanilla.lua:770
 SelectGossipID = <function> defined @Capping/Core_Vanilla.lua:799
 StartBar = <function> defined @Capping/Core_Vanilla.lua:100
 EnterZone = <function> defined @Capping/Modules/AlteracValley_Vanilla.lua:241
 StopAllBars = <function> defined @Capping/Core_Vanilla.lua:168
 GOSSIP_SHOW = <function> defined @Capping/Modules/AlteracValley_Vanilla.lua:23
 QUEST_COMPLETE = <function> defined @Capping/Modules/AlteracValley_Vanilla.lua:147
 StopScoreEstimator = <function> defined @Capping/Core_Vanilla.lua:553
 GetGossipID = <function> defined @Capping/Core_Vanilla.lua:790
 QUEST_PROGRESS = <function> defined @Capping/Modules/AlteracValley_Vanilla.lua:132
 CHAT_MSG_ADDON = <function> defined @Capping/Modules/AlteracValley_Vanilla.lua:219
 GetGossipAvailableQuestID = <function

**Comment by funkydude** [comment]
Thanks!
