### ISSUE TITLE
Can you report the Siege Engine's HP across the Capping bars in IOC, like Boss Healths in AV/Ashran?

### ISSUE THREAD

**Issue by mesostealthy** [BigWigsMods/Capping#144]
## Describe the problem
There can be 2 Siege Engines up in Isle of Conquest. It would be nice if you could put up a Capping bar for it like you have done for the Bosses in Alterac Valley and Ashran. Rarely are both ever up, but one side can have one, and then another caps Workshop and if the previous SIege did not die yet, another will spawn for the other team. Could be red/blue bars to indicate the faction for each unit.

### What steps will reproduce the problem?

1.  Not a bug, more like afeature to be requested.
2.  
3.  

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
Screenshot does not apply here.

### What version of the addon are you using? (Stating 'latest' is not useful)
This also does not apply, as it's not a bug report.

### Do you have an error log of what happened?
Not an error.

### Any additional information? (example: WoW language if not English)
The Siege Engine can not be targetted anywhere on the map, so it would have to work more like how the bosses are tracked in Ashran. With someone having it targetted or set on focus to relay out to other users with Capping.

**Comment by funkydude** [comment]
Last I checked this thing can die in <20 seconds, I don't really see the benefit?

**Comment by mesostealthy** [comment]
The respawn timer is already implemented for it, it just would be nice to track it's HP to know if you have something heading up to the Hangar earlier rather than later.

**Comment by funkydude** [comment]
The respawn bar is quite a long duration so it's worthwhile information. Is it really worthwhile to display a bar that could be there for <10sec?

**Comment by mesostealthy** [comment]
I think the more important part to relay is where it is on the map, the HP may not need to be know, but if you are at the Docks and it's heading to the Hangar, it would be useful information to know the coordinates of the vehicle imo.

**Comment by funkydude** [comment]
I don't think that's even possible, coordinates are locked down in instances like raids and battlegrounds.

**Comment by mesostealthy** [comment]
Don't really need the coordinates per say, but the HP on it when some one else has it targeted to be relayed with other Capping users like boss HP in Ashran is more of what I had in mind.
