### ISSUE TITLE
[Suggestion] Timer for Wintergrasp

### ISSUE THREAD

**Issue by wheatbread** [BigWigsMods/Capping#145]
## Describe the problem

Would like to suggest the option to have a timer showing before Wintergrasp starts.  Would be very useful for knowing how far off/ soon it is and planning activities accordingly. 

### What steps will reproduce the problem?

1.  
2.  
3.

**Comment by funkydude** [comment]
I'm not sure there's even any point anymore at this stage of the expansion with Cataclysm around the corner.

I'm not even sure how it would interact with the different layers and there's probably addons already doing it.
