### ISSUE TITLE
AV Quest Error

### ISSUE THREAD

**Issue by Belden1** [BigWigsMods/Capping#147]
### What steps will reproduce the problem?

1.  Enter AV
2.  Bring materials to NPC in horde base
3.  Quest error

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![image](https://github.com/BigWigsMods/Capping/assets/16743375/42ad9432-da65-45cd-8049-f0c518c314d1)

### What version of the addon are you using? (Stating 'latest' is not useful)
A v10.2.9-1-gad1d12d

### Do you have an error log of what happened?
See image

**Comment by funkydude** [comment]
Classic Era or Cataclysm?

**Comment by Belden1** [comment]
> Classic Era or Cataclysm?

Classic Era, as the issue was selected

**Comment by funkydude** [comment]
We don't have an issue selection for Cataclysm, hence the question...
