### ISSUE TITLE
Clickable flag carrier names on WSG and TP on BG info frame

### ISSUE THREAD

**Issue by xeropresence** [BigWigsMods/Capping#15]
Is this something capping provided?

![image](https://user-images.githubusercontent.com/16833/47191370-c1f08a80-d33e-11e8-87b0-b26bac2656c0.png)

I had this during legion and assumed it was something capping was providing, with BFA it's no longer present and I can't think of any other addons I was running that would have added that.

**Comment by funkydude** [comment]
It *was* provided. However it is no longer necessary as the arena frames provide this information.

**Comment by xeropresence** [comment]
Not a big fan of the arena frames.  That info was compact and concise, while the arena frames are the direct opposite. Can this feature be restored?

**Comment by funkydude** [comment]
It's not a matter of simply restoring it, it would need re-written for 8.0, which I have no interest in. Good unit frame addons tend to support arena frames and thus you can tweak them as you wish.

**Comment by xeropresence** [comment]
I use suf, which supports arena frames but afaik cannot display differently based on BG and Arena. If I rewrite and issue a PR would you accept it?

**Comment by funkydude** [comment]
I also use SUF and I am happy with using the same layout for arena & BG. I cannot guarantee I'd accept a PR, it depends on the quality. I'm not really interested in a hackjob that simply makes it work. The best chance of getting it accepted would be creating a "proper" arena frame hardcoded to arena1 and arena2.
