### ISSUE TITLE
Eots score prediction in RBGs

### ISSUE THREAD

**Issue by xeropresence** [BigWigsMods/Capping#16]
Was looking at the code and it looks like eots should have score prediction, in rbgs this doesn't function. Its a different zoneid which could be the issue.

**Comment by funkydude** [comment]
I don't do RBGs so you'd need to fetch multiple IDs for me including:
```
/dump UnitPosition("player")
/dump C_Map.GetBestMapForUnit("player")
```

A bit more complex as it will produce multiple chat prints but also needed:
```
/run local f=CreateFrame("Frame"); f:RegisterEvent("UPDATE_UI_WIDGET"); f:SetScript("OnEvent", function(f,e,t) print(t.widgetID) end)
```

**Comment by xeropresence** [comment]
[02:07:43] Dump: value=UnitPosition("player")
[02:07:43] [4]=968
[02:07:46] Dump: value=C_Map.GetBestMapForUnit("player")
[02:07:46] [1]=397

Then for the third script
[02:07:49] 704
[02:07:49] 705
[02:07:51] 704
[02:07:51] 705
[02:07:51] 1317
[02:07:51] 1315
[02:07:51] 1315
[02:07:51] 1315
[02:07:51] 1311
[02:07:53] 704
[02:07:53] 705
[02:07:55] 704

**Comment by funkydude** [comment]
I just took a guess in regards to which is the alliance and which is the horde widget. if you can, try
```
/dump C_UIWidgetManager.GetIconAndTextWidgetVisualizationInfo(705)
```

It should mention horde in one of the outputs?

**Comment by xeropresence** [comment]
Can't easily check that but,

According to UiWidgetStringSource.db2,

There are two fields with ParentWidgetId = 704 which contains the strings
Bases: %1779w  Resources: %1776w/%1780w
Alliance status
The Alliance have the flag


And for 705
Bases: %1778w  Resources: %1777w/%1780w
Horde status
The Horde have the flag

No rows with parentwidgetid = 1311,1315,1317

**Comment by funkydude** [comment]
Should be fine then, cheers.
