### ISSUE TITLE
IoC German mechanic quotes

### ISSUE THREAD

**Issue by yoshimo** [BigWigsMods/Capping#17]
the deDE.lua has no entry for the workshop quotes.
The Horde mechanic quotes are as follows:

[CHAT_MSG_MONSTER_YELL] Ich arbeite an der Belagerungsmaschine. Haltet mir einfach nur den Rücken frei. Benutzt diese Zephyriumbomben an den Toren, solltet Ihr sie brauchen!#Goblinmechaniker###Alicja##0#0##0#820#nil#0#false#false#false#false", -- [1]

[CHAT_MSG_MONSTER_YELL] Schon wieder kaputt?! Ich werde es richten... Ihr solltet allerdings nicht davon ausgehen, dass das noch unter die Garantie fällt.#Goblinmechaniker###Belagerungsmaschine##0#0##0#928#nil#0#false#false#false#false", -- [6]

**Comment by funkydude** [comment]
There is an entry in the deDE file, right here commented out: https://github.com/BigWigsMods/Capping/blob/ce2189ce4a6cb4a71a95a2059085ebed306147bc/Locales/deDE.lua#L23-L30

As I need the alliance yells also, I'll wait until someone posts them before adding this. You can get the alliance yells as a horde simply by waiting for alliance to cap it.

**Comment by funkydude** [comment]
I assume you're aware you only posted 1 of them?

**Comment by yoshimo** [comment]
Work in progress, it is quite difficult to find a match where the alliance gets the workshop but the horde is powerful enough to kill the tank afterwards.

**Comment by yoshimo** [comment]
`[CHAT_MSG_MONSTER_YELL] Es ist schon kaputt?! Ach, keine Sorge, nichts, was ich nicht reparieren kann.#Gnomenmechaniker###Belagerungsmaschine##0#0##0#1090#nil#0#false#false#false#false", -- [17267]`

**Comment by yoshimo** [comment]
--L.hordeGate = "Hordentor"
--L.allianceGate = "Allianztor"

**Comment by funkydude** [comment]
@yoshimo 
I'm using Google translate and this Horde (goblin) yell seems incorrect:

> [CHAT_MSG_MONSTER_YELL] Ich arbeite an der Belagerungsmaschine. Haltet mir einfach nur den Rücken frei. Benutzt diese Zephyriumbomben an den Toren, solltet Ihr sie brauchen!#Goblinmechaniker###Alicja##0#0##0#820#nil#0#false#false#false#false", -- [1]

That yells seems like the one right after you cap the workshop, not the halfway yell. The alliance (gnome) one seems correct.

**Comment by yoshimo** [comment]
Copy&paste mistake

Ich hab's gleich! Haltet mir die Allianz vom Leib. Kämpfen steht nicht in meinem Vertrag!#Goblinmechaniker###
