### ISSUE TITLE
7.1.3 error upon entering random bg (strand of ancients)

### ISSUE THREAD

**Issue by ceylina** [BigWigsMods/Capping#2]
This popped up upon entering a random BG - in this case strand of the ancients

1x Capping\battlegrounds-Battlegrounds.lua:412: attempt to index global 'AlwaysUpFrame1' (a nil value)
Capping\battlegrounds-Battlegrounds.lua:412: in function `func'
Capping\core.lua:47: in function `CheckCombat'
Capping\battlegrounds-Battlegrounds.lua:428: in function <Capping\battlegrounds.lua:421>
Capping\battlegrounds-Battlegrounds.lua:479: in function `func'
Capping\core.lua:357: in function `?'
Capping\core.lua:36: in function <Capping\core.lua:35>

Locals:
(*temporary) = <function> defined =[C]:-1
(*temporary) = CappingEotSFrame {
 0 = <userdata>
 text = <unnamed> {
 }
}
(*temporary) = "LEFT"
(*temporary) = UIParent {
 0 = <userdata>
 firstTimeLoaded = 1
 variablesLoaded = true
}
(*temporary) = "BOTTOMLEFT"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'AlwaysUpFrame1' (a nil value)"
ef = CappingEotSFrame {
 0 = <userdata>
 text = <unnamed> {
 }
}

**Comment by funkydude** [comment]
Thanks, will look into this.
