### ISSUE TITLE
8.1 error report.

### ISSUE THREAD

**Issue by Wizardling** [BigWigsMods/Capping#20]
2x Capping\battlegrounds-Battlegrounds.lua:191: attempt to index local 'dataTbl' (a nil value)
Capping\battlegrounds-Battlegrounds.lua:191: in function `?'
Capping\Capping-v8.0.21.lua:51: in function <Capping\Capping.lua:50>

Locals:
self = <table> {
 GetBar = <function> defined @Capping\Capping.lua:460
 PLAYER_LOGIN = <function> defined @Capping\Capping.lua:83
 AREA_POIS_UPDATED = <function> defined @Capping\battlegrounds.lua:126
 RestartSiegeBar = <function> defined @Capping\battlegrounds.lua:846
 StartBar = <function> defined @Capping\Capping.lua:392
 ScorePredictor = <function> defined @Capping\battlegrounds.lua:179
 L = <table> {
 }
 WSGGetTimeRemaining = <function> defined @Capping\battlegrounds.lua:888
 UpdateBases = <function> defined @Capping\battlegrounds.lua:248
 WSGFlagCarrier = <function> defined @Capping\battlegrounds.lua:881
 prevTimer = 460853.927000
 ZONE_CHANGED_NEW_AREA = <function> defined @Capping\Capping.lua:158
 StopBar = <function> defined @Capping\Capping.lua:441
 IoCSync = <function> defined @Capping\battlegrounds.lua:779
 START_TIMER = <function> defined @Capping\Capping.lua:64
 AVSync = <function> defined @Capping\battlegrounds.lua:501
 CheckGateHealth = <function> defined @Capping\battlegrounds.lua:674
 RegisterEvent = <function> defined @Capping\Capping.lua:57
 HealthUpdate = <function> defined @Capping\battlegrounds.lua:363
 AddBG = <function> defined @Capping\Capping.lua:152
 UPDATE_BATTLEFIELD_STATUS = <function> defined @Capping\Capping.lua:225
 Test = <function> defined @Capping\Capping.lua:304
 UnregisterEvent = <function> defined @Capping\Capping.lua:60
 RegisterTempEvent = <function> defined @Capping\Capping.lua:53
}
t = 461482.774000
ascore = 0
abases = 0
dataTbl = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = 914
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'dataTbl' (a nil value)"
updateBases = true
prevTime = 461482.774000
GetIconAndTextWidgetVisualizationInfo = <function> defined =[C]:-1
allianceWidget = 914
strmatch = <function> defined =[C]:-1
tonumber = <function> defined =[C]:-1
hordeWidget = 915
ppsTable = <table> {
 1 = 1
 2 = 1.500000
 3 = 2
 4 = 3.500000
 5 = 30
}
MaxScore = 1500
ceil = <function> defined =[C]:-1
format = <function> defined =[C]:-1
L = <table> {
 halfway = "halfway"
 allianceGate = "Alliance Gate"
 hordeBoss = "Horde Boss"
 hasTakenTheTrigger = "has taken the"
 balinda = "Balinda Stonehearth"
 galvangar = "Galvangar"
 allianceBoss = "Alliance Boss"
 upgradeToTrigger = "Upgrade to"
 hordeGate = "Horde Gate"
 droppedTrigger = "dropped"
 capturedTheTrigger = "captured the"
 takenTheFlagTrigger = "^(.+) has taken the flag!"
 broken = "broken"
 finalScore = "Final: %d - %d"
 battleBegins = "Battle Begins"
 flagRespawns = "Flag respawns"
}
prevText = "Final: 1500 - 460"
hordeWinning = false

**Comment by funkydude** [comment]
This looks like it happened in Snowy AB, but I cannot reproduce it. Works fine for me.

Will need further info such as what point of time exactly it happened, and where.
