### ISSUE TITLE
Not in game

### ISSUE THREAD

**Issue by Kalyendra** [BigWigsMods/Capping#21]
The addon will not show up in my game. It isn't appearing on my addon list. I downloaded it through twitch.

**Comment by funkydude** [comment]
This isn't a support forum. If it's not in the addon list then it's not installed. Open an issue with Curse/Twitch support or install it manually.

**Comment by Kalyendra** [comment]
It is in the proper folder. I installed it through twitch. When that did
not work I Uninstalled it and placed it in the proper folder manually. That
did not work either. I asked multiple players in game and some said they
had tried as well and it did not work for them. That is why I brought the
issue to your attention.

**Comment by funkydude** [comment]
@Kalyendra You specifically mentioned it does not show up in the addons list at the character selection screen. That means WoW is not detecting it and there is nothing I can really do for you in terms of recommendations. It works fine for hundreds of thousands of other people.

**Comment by Kalyendra** [comment]
It shows on the add on list in twitch but not in game. It also shows the
folder in my wow files. I thought someone would want to take a look at it
as some people I've spoken with have no problem while others have told me
it's buggy. I found a different addon that does the same thing
