### ISSUE TITLE
Isle of Conquest

### ISSUE THREAD

**Issue by Eveliarix** [BigWigsMods/Capping#26]
The gate health percent will not show for me. They did only one time in the past few days, I have tried disabling all of my other addons except this one to make sure none were conflicting. A few others I was PVPing with had the same issue.

**Comment by funkydude** [comment]
This is normal when joining the game after the warmup timer has ended.

**Comment by Eveliarix** [comment]
I am always in before the timer has ended, but thank you for the reply!

**Comment by funkydude** [comment]
Can you show us a screenshot of this?

**Comment by Eveliarix** [comment]
I actually finally got it working last night! I deleted my cache and it seems to be working fine now. Thank you!
