### ISSUE TITLE
time to win estimations no longer showing in RBGs

### ISSUE THREAD

**Issue by xeropresence** [BigWigsMods/Capping#27]
Gilneas had no win timer. I don't think EOTS did either. Should I run that script you had me run last time for the rbgs I notice it not running for?

**Comment by funkydude** [comment]
Thanks but this isn't an RGB issue. There were changes made in 8.1.5 that I need to adjust for. If there's any special changes also made for RGB I'm not sure yet but I'll let you know.

**Comment by funkydude** [comment]
EotS score prediction & capture timers should both be working again.
