### ISSUE TITLE
Lua error during "Brawl: Warsong Scramble" event

### ISSUE THREAD

**Issue by RaphMad** [BigWigsMods/Capping#3]
When using capping during the described event, I get lots (hundreds) of the following LUA errors:

_FrameXML\WorldMapFrame.lua:2502: attempt to index local 'flagFrame' (a nil value)
FrameXML\WorldMapFrame.lua:2502: in function <FrameXML\WorldMapFrame.lua:2374>_

**Comment by funkydude** [comment]
Nothing to do with Capping. Blizzard bug.

**Comment by RaphMad** [comment]
Thanks for your quick response - are you 100% sure this is simply a blizzard bug?

I'm well aware it is not directly pointing to Capping code, but it definitely only happened with Capping active and did not happen when deactivating it.

**Comment by funkydude** [comment]
It happens when there are more than 4 flags to render.

**Comment by RaphMad** [comment]
Thanks a lot for the clarification - this condition (<4 active flags) may have interferred with my activating/deactivating times and thus led me to this false conclusion :).
