### ISSUE TITLE
Sounds for Wintergrasp warnings

### ISSUE THREAD

**Issue by Dasubertakem** [BigWigsMods/Capping#30]
Playing the Queue sound over the master channel is fine, but the addon making noise when it alerts me of things like walls breaking in wintergrasp is not. You want to blast that in chat to me, that's fine. Don't make it a raid warning blast. Text is enough. I don't like addons that make noise. If you want that to be the default sure, that's your prerogative, but give me the option to make it STFU. I like the addon for it's timers on bases and towers, I like the data it presents, but the excess sound is not wanted.

**Comment by funkydude** [comment]
This won't be changed. However, since this is actually Blizzard playing this sound due to Capping adding the warnings, they will be played over the "sound effects" channel, not the "master" channel. So you can either adjust that slider or edit the code in your local copy.
