### ISSUE TITLE
Gate Timers not displaying for Isle of Conquest

### ISSUE THREAD

**Issue by foxofsnow** [BigWigsMods/Capping#32]
Gates no longer display within the Capping tooltip for Isle of Conquest. Also, bosses sometimes show, but not all the time (specifically for the opposing team)

**Comment by funkydude** [comment]
> Gates no longer display within the Capping tooltip for Isle of Conquest.

What does this mean? Gate health displays as a bar not a tooltip.

> Also, bosses sometimes show, but not all the time (specifically for the opposing team)

Boss health shows when capping users are near them. This is working fine.

**Comment by funkydude** [comment]
No response, closing.
