### ISSUE TITLE
Feature Request: Option to Turn off auto turnins in AV

### ISSUE THREAD

**Issue by eramocki** [BigWigsMods/Capping#35]
WIth 8.2, they added a new quest that gives 1500 honor for a single Storm Crystal turnin. Unfortunately, it is currently impossible to complete this quest with this addon since it on the same quest giver as the auto turnin quest vendor. Could you please add an option to turn off auto turnins in AV?

**Comment by funkydude** [comment]
No need. Just changed it to auto select the quest first.

Thanks for letting me know!
