### ISSUE TITLE
Isle of conquest

### ISSUE THREAD

**Issue by OMELETPANTS** [BigWigsMods/Capping#36]
Doesnt always show status of horde and alliance gates. Inconsistent in what information it provides

**Comment by funkydude** [comment]
Thanks for the report. Unfortunately unless you join the BG prior to the gates opening (the game starting) then there is no guarantee you will see gate health.

**Comment by OMELETPANTS** [comment]
Hi, I run this BG a lot and almost every time I'm there before the game starts/gates open. 

Over the last couple of weeks the app has been buggy. Much of the time it doesn't show progress on either gates. 25% of the time it will. 

Then on refinery and quarry it only shows status about half the time.

On bosses it will not always show progress on the opponents even though both teams are attacking the boss.

Love the app and it works great on the other BGs.


Bob Rosenberger
rsnbrgr@mac.com
847-612-9117



On Jul 9, 2019, at 9:48 PM, funkydude <notifications@github.com> wrote:

Thanks for the report. Unfortunately unless you join the BG prior to the gates opening (the game starting) then there is no guarantee you will see gate health.

**Comment by OMELETPANTS** [comment]
WERE YOU ABLE TO FIND ANY ISSUES?

**Comment by funkydude** [comment]
The issue with gate health not showing when you join before the gates open is resolved.
There are no issues with refinery or quarry bars.
Boss health is working as intended - requires a Capping user nearby the NPC.
