### ISSUE TITLE
translation ruRU

### ISSUE THREAD

**Issue by Gizmi** [BigWigsMods/Capping#41]
if GetLocale() ~= "ruRU" then return end
local _, mod = ...
local L = mod.L

L.battleBegins = "Начало сражения"
L.finalScore = "Финал: %d - %d"
L.flagRespawns = "Появление Флагов"

L.takenTheFlagTrigger = "^(.+) захватывает флаг!"
L.hasTakenTheTrigger = "захватил"
L.upgradeToTrigger = "обновлено до"
L.droppedTrigger = "уронил"
L.capturedTheTrigger = "захватил"

L.hordeGate = "Ворота Орды"
L.allianceGate = "Ворота Альянса"
L.gatePosition = "%s (%s)"
L.west = "Запад"
L.front = "Центр"
L.east = "Восток"
L.hordeBoss = "Босс Орды"
L.allianceBoss = "Босс Альянса"
L.galvangar = "Гальвангар" -- Капитан Гальвангар 
L.balinda = "Балинда" -- Капитан Балинда Каменный Очаг
L.ivus = "Ивус" -- Ивус Лесной Властелин
L.lokholar = "Локолар" -- Локолар Владыка Льда
L.handIn = "|cFF33FF99Capping|r: Автоматическая сдача квестовых предметов."

--- Alliance IoC Workshop yells:
-- Gnomish Mechanic yells: I'm halfway there! Keep the Horde away from here.  They don't teach fighting in engineering school!
-- Gnomish Mechanic yells: It's broken already?! No worries. It's nothing I can't fix.
--- Horde IoC Workshop yells:
-- Goblin Mechanic yells: I'm about halfway done! Keep the Alliance away - fighting's not in my contract!
-- Goblin Mechanic yells: It's broken again?! I'll fix it... just don't expect the warranty to cover this.
L.halfway = "наполовину"
L.broken = "сломано"

-- Wintergrasp
L.damaged = "|cFF33FF99Capping|r: %s Разрушено"
L.destroyed = "|cFF33FF99Capping|r: %s Уничтожено"
L.northEastKeep = "Северо-восточная башня крепости"
L.southEastKeep = "Юго-восточная башня крепости"
L.northWestKeep = "Северо-западная башня крепости"
L.southWestKeep = "Юго-западная башня крепости"
L.northWest = "Северо-западная стена"
L.southWest = "Юго-западная  стена"
L.south = "Южная стена"
L.southEast = "Северо-западная стена"
L.northEast = "Северо-восточная стена"
L.innerWest = "Внутренняя-западная стена"
L.innerSouth = "Внутренняя-южная стена"
L.innerEast = "Внутренняя-восточная стена"
L.southGate = "Южные ворота"
L.mainEntrance = "Главный вход"
L.westTower = "Западная башня"
L.southTower = "Южная башня"
L.eastTower = "Восточная башня"

**Comment by Gizmi** [comment]
part translated

**Comment by Gizmi** [comment]
To translate NPC replicas, you need to go to the BG and just copy it, in a couple of days I can do.

**Comment by funkydude** [comment]
Thanks, I will wait until you are finished.
There is also the locale file in the `Options` folder.

**Comment by Gizmi** [comment]
if GetLocale() ~= "ruRU" then return end
local _, mod = ...
local L = mod.L

-- Options
--L.general = "Основные"
--L.test = "Тест"
L.lock = "Закреплен"
L.barIcon = "Иконка полоски"
L.showTime = "Показ времени"
L.fillBar = "Заполнение полоски"
L.font = "Шрифт"
L.fontSize = "Размер шрифта"
L.monochrome = "Монохромный текст"
L.outline = "Контур"
L.none = "Нет"
L.thin = "Тонкий"
L.thick = "Толстый"
L.texture = "Текстура"
L.barSpacing = "Расстояние полоски"
L.barWidth = "Ширина полоски"
L.barHeight = "Высота полоски"
--L.alignText = "Выровнять текст"
L.alignTime = "Выровнить время"
--L.alignIcon = "Выровнять иконку полосы"
L.left = "Влево"
L.center = "По центру"
L.right = "Вправо"
L.growUpwards = "Направить вверх"
L.textColor = "Цвет текста"
--L.allianceBars = "Полосы Альянса"
--L.hordeBars = "Полоса Орды"
--L.queueBars = "Полоса очереди"
--L.otherBars = "Другие полосы"
L.barBackground = "Задний план полоски"

-- Features
--L.features = "Характеристики"
--L.queueBarsDesc = "Включить столбцы, показывающие к каким очередям вы присоединились и примерное время, которое вы будете в ожидать очереди."
--L.barClickDesc = "Сконфигурируйте модификатор клавиатуры, который вы хотите использовать для конкретного вывода чата при нажатии на полосу. Установка всех 3 на «Нет» отключит кликабельные панели, позволяя вам нажимать на них насквозь."
--L.shiftClick = "Shift-Click"
--L.controlClick = "Control-Click"
--L.altClick = "Alt-Click"
--L.sayChat = "Сообщить в чат(рейда)"
--L.raidChat = "Чат группы"
--L.clickableBars = "Кликабельные полосы"
--L.loudQueue = "Loud Queue"
--L.loudQueueDesc = "Когда очередь подойдёт к концу, звуковое уведомление будет воспроизведено по звуковому каналу «Основной».."

**Comment by Gizmi** [comment]
"Shift-Click"
"Control-Click"
"Alt-Click"
not necessarily translate

**Comment by Gizmi** [comment]
> 
> 
> done

**Comment by Gizmi** [comment]
For Russian = есть ошибки или всё ок?

**Comment by funkydude** [comment]
--- Alliance IoC Workshop yells:
```
-- Gnomish Mechanic yells: I'm halfway there! Keep the Horde away from here. They don't teach fighting in engineering school!
-- Gnomish Mechanic yells: It's broken already?! No worries. It's nothing I can't fix.
```
--- Horde IoC Workshop yells:
```
-- Goblin Mechanic yells: I'm about halfway done! Keep the Alliance away - fighting's not in my contract!
-- Goblin Mechanic yells: It's broken again?! I'll fix it... just don't expect the warranty to cover this.
```

You need to replace these with the yells from Isle of Conquest.

**Comment by Gizmi** [comment]
I need help here. Yesterday I played 2 games but I didn’t see this chat message.

**Comment by Gizmi** [comment]
Гоблинский механик кричит: я на полпути! Держите Альянс подальше - боевые действия не входят в мой контракт! - Механик Гоблин кричит: «Он снова сломан ?!» Я исправлю это ... просто не ожидайте, что гарантия покроет это.

**Comment by Gizmi** [comment]
done

**Comment by funkydude** [comment]
You need to wait for alliance to capture the middle so you can get the 2 gnome yells which are missing.

**Comment by Gizmi** [comment]
I have no identity for the alliance, please make it as it is

**Comment by funkydude** [comment]
> I have no identity for the alliance

Do you mean you don't have an alliance character?
You don't need an alliance character.
Join Isle of Conquest as Horde, wait until the alliance capture the middle, then you will see the gnome yells.

>please make it as it is

Not until you can provide the gnome yells.

**Comment by funkydude** [comment]
Closed by b7a826e81f97775090e4b1788fb7794a1e8a9b47
