### ISSUE TITLE
Auto Quest Turn-In Options

### ISSUE THREAD

**Issue by Tuhljin** [BigWigsMods/Capping#47]
Currently, Alterac Valley has automatic quest turn-ins. I'd prefer if this was an optional setting, since sometimes I want to read the quest text and I don't think people should have to choose between that and having the main feature of this addon, battleground timers.

Ideally, the options would be something like:
- AV auto turn-in off
- AV auto turn-in always
- AV auto turn-in when (chosen modifier key) is held

**Comment by minestra** [comment]
Yeah I deleted it because of that. Great addon trash feature to hide.

**Comment by vioray** [comment]
did it work? that feature definitely needs a disable option

**Comment by minestra** [comment]
Yup it's like maybe 20 lines I just deleted.

**Comment by Vizcro** [comment]
Uhm, is there any hope this will make it into the addon anytime soon, seeing this thread is from 2019? This would be a VERY welcome addition.

**Comment by funkydude** [comment]
Sorry it took so long, added in latest release.
