### ISSUE TITLE
Lua Errors after latest patch, inside and outside BGs (wow classic)

### ISSUE THREAD

**Issue by dinkmaster** [BigWigsMods/Capping#48]
I keep getting these errors inside and outside BGs

`Message: Interface\AddOns\Capping\Capping.lua:72: attempt to index global 'TimerTracker' (a nil value)
Time: Wed Dec 11 11:35:35 2019
Count: 1
Stack: Interface\AddOns\Capping\Capping.lua:72: attempt to index global 'TimerTracker' (a nil value)
Interface\AddOns\Capping\Capping.lua:72: in function `?'
Interface\AddOns\Capping\Capping.lua:56: in function <Interface\AddOns\Capping\Capping.lua:55>

Locals: self = <table> {
 AVTurnIn = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:618
 GetBar = <function> defined @Interface\AddOns\Capping\Capping.lua:464
 CheckTowerHealth = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:1114
 PLAYER_LOGIN = <function> defined @Interface\AddOns\Capping\Capping.lua:87
 AREA_POIS_UPDATED = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:153
 RestartSiegeBar = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:964
 StartBar = <function> defined @Interface\AddOns\Capping\Capping.lua:396
 ScorePredictor = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:281
 WGSync = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:1193
 L = <table> {
 }
 AVTurnInComplete = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:673
 AVTurnInProgress = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:663
 ZONE_CHANGED_NEW_AREA = <function> defined @Interface\AddOns\Capping\Capping.lua:162
 StopBar = <function> defined @Interface\AddOns\Capping\Capping.lua:445
 IoCSync = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:897
 START_TIMER = <function> defined @Interface\AddOns\Capping\Capping.lua:69
 AVSync = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:597
 CheckGateHealth = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:789
 RegisterEvent = <function> defined @Interface\AddOns\Capping\Capping.lua:62
 HealthUpdate = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:450
 AddBG = <function> defined @Interface\AddOns\Capping\Capping.lua:156
 UPDATE_BATTLEFIELD_STATUS = <function> defined @Interface\AddOns\Capping\Capping.lua:229
 Test = <function> defined @Interface\AddOns\Capping\Capping.lua:308
 UnregisterEvent = <function> defined @Interface\AddOns\Capping\Capping.lua:65
 RegisterTempEvent = <function> defined @Interface\AddOns\Capping\Capping.lua:58
}
_ = 1
timeSeconds = 4
_ = "Alterac Valley"
t = "pvp"
(*temporary) = 1
(*temporary) = nil
(*temporary) = ""
(*temporary) = 0
(*temporary) = 0
(*temporary) = false
(*temporary) = 30
(*temporary) = 0
(*temporary) = "attempt to index global 'TimerTracker' (a nil value)"
L = <table> {
 lokholar = "Lokholar"
 hordeBoss = "Horde Boss"
 destroyed = "Capping: %s destroyed"
 damaged = "Capping: %s damaged"
 droppedTrigger = "dropped"
 southGate = "South gate"
 south = "South wall"
 capturedTheTrigger = "captured the"
 handIn = "Capping: Automatically handing in quest items."
 balinda = "Balinda"
 halfway = "halfway"
 allianceGate = "Alliance Gate"
 mainEntrance = "Main entrance"
 allianceBoss = "Alliance Boss"
 broken = "broken"
 battleBegins = "Battle Begins"
 flagRespawns = "Flag respawns"
 southTower = "South Tower"
 westTower = "West Tower"
 upgradeToTrigger = "Upgrade to"
 southEast = "South-East wall"
 finalScore = "Final: %d - %d"
 innerWest = "Inner-West wall"
 hasTakenTheTrigger = "has taken the"
 eastTower = "East Tower"
 northEast = "North-East wall"
 southWest = "South-West wall"
 innerSouth = "Inner-South wall"
 ivus = "Ivus"
 takenTheFlagTrigger = "^(.+) has taken the flag!"
 innerEast = "Inner-East wall"
 galvangar = "Galvangar"
 northWest = "North-West wall"
 hordeGate = "Horde Gate"
}
mod = <table> {
 AVTurnIn = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:618
 GetBar = <function> defined @Interface\AddOns\Capping\Capping.lua:464
 CheckTowerHealth = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:1114
 PLAYER_LOGIN = <function> defined @Interface\AddOns\Capping\Capping.l`

`Message: Interface\AddOns\Capping\battlegrounds.lua:544: attempt to call upvalue 'GetScoreInfo' (a nil value)
Time: Wed Dec 11 11:35:37 2019
Count: 1
Stack: Interface\AddOns\Capping\battlegrounds.lua:544: attempt to call upvalue 'GetScoreInfo' (a nil value)
Interface\AddOns\Capping\battlegrounds.lua:544: in function <Interface\AddOns\Capping\battlegrounds.lua:542>

Locals: (for index) = 1
(for limit) = 80
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to call upvalue 'GetScoreInfo' (a nil value)"
GetScoreInfo = nil
hereFromTheStart = true
hasData = true
Timer = <function> defined =[C]:-1
allow = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:540
stopTimer = nil
NewTicker = <function> defined @Interface\SharedXML\C_TimerAugment.lua:11
stop = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:541
`

`Message: Interface\AddOns\Capping\Capping.lua:275: attempt to call global 'GetNumBattlegroundTypes' (a nil value)
Time: Wed Dec 11 11:44:41 2019
Count: 14
Stack: Interface\AddOns\Capping\Capping.lua:275: attempt to call global 'GetNumBattlegroundTypes' (a nil value)
Interface\AddOns\Capping\Capping.lua:275: in function `?'
Interface\AddOns\Capping\Capping.lua:56: in function <Interface\AddOns\Capping\Capping.lua:55>

Locals: self = <table> {
 AVTurnIn = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:618
 GetBar = <function> defined @Interface\AddOns\Capping\Capping.lua:464
 CheckTowerHealth = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:1114
 PLAYER_LOGIN = <function> defined @Interface\AddOns\Capping\Capping.lua:87
 AREA_POIS_UPDATED = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:153
 RestartSiegeBar = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:964
 StartBar = <function> defined @Interface\AddOns\Capping\Capping.lua:396
 ScorePredictor = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:281
 WGSync = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:1193
 L = <table> {
 }
 AVTurnInComplete = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:673
 AVTurnInProgress = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:663
 ZONE_CHANGED_NEW_AREA = <function> defined @Interface\AddOns\Capping\Capping.lua:162
 StopBar = <function> defined @Interface\AddOns\Capping\Capping.lua:445
 IoCSync = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:897
 START_TIMER = <function> defined @Interface\AddOns\Capping\Capping.lua:69
 AVSync = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:597
 CheckGateHealth = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:789
 RegisterEvent = <function> defined @Interface\AddOns\Capping\Capping.lua:62
 HealthUpdate = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:450
 AddBG = <function> defined @Interface\AddOns\Capping\Capping.lua:156
 UPDATE_BATTLEFIELD_STATUS = <function> defined @Interface\AddOns\Capping\Capping.lua:229
 Test = <function> defined @Interface\AddOns\Capping\Capping.lua:308
 UnregisterEvent = <function> defined @Interface\AddOns\Capping\Capping.lua:65
 RegisterTempEvent = <function> defined @Interface\AddOns\Capping\Capping.lua:58
}
queueId = 1
status = "queued"
map = "Alterac Valley"
_ = 0
_ = 0
_ = false
size = false
_ = "Eastern Kingdoms"
zoneType = "none"
esttime = 205.059000
waited = 195
estremain = 10.059000
bar = nil
icon = nil
(*temporary) = 1
(*temporary) = nil
(*temporary) = "attempt to call global 'GetNumBattlegroundTypes' (a nil value)"
GetBattlefieldStatus = <function> defined =[C]:-1
format = <function> defined =[C]:-1
ARENA = "Arena"
GetBattlefieldPortExpiration = <function> defined =[C]:-1
db = <table> {
 SetProfile = <function> defined @Interface\AddOns\Accountant_Classic\Libs\AceDB-3.0\AceDB-3.0.lua:430
 defaults = <table> {
 }
 callbacks = <table> {
 }
 RegisterDefaults = <function> defined @Interface\AddOns\Accountant_Classic\Libs\AceDB-3.0\AceDB-3.0.lua:398
 CopyProfile = <function> defined @Interface\AddOns\Accountant_Classic\Libs\AceDB-3.0\AceDB-3.0.lua:549
 ResetProfile = <function> defined @Interface\AddOns\Accountant_Classic\Libs\AceDB-3.0\AceDB-3.0.lua:584
 keys = <table> {
 }
 UnregisterAllCallbacks = <function> defined @Interface\AddOns\Accountant_Classic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 DeleteProfile = <function> defined @Interface\AddOns\Accountant_Classic\Libs\AceDB-3.0\AceDB-3.0.lua:510
 sv = <table> {
 }
 profile = <table> {
 }
 RegisterCallback = <function> defined @Interface\AddOns\Accountant_Classic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetNamespace = <function> defined @Interface\AddOns\Accountant_Classic\Libs\AceDB-3.0\AceDB-3.0.lua:676
 ResetDB = <function> defined @Interface\AddOns\Accountant_Classic\Libs\AceDB-3.0\AceDB-3.0.lua:612
 Unreg`

`Message: Interface\AddOns\Capping\Capping.lua:288: attempt to call global 'GetNumBattlegroundTypes' (a nil value)
Time: Wed Dec 11 11:46:41 2019
Count: 8
Stack: Interface\AddOns\Capping\Capping.lua:288: attempt to call global 'GetNumBattlegroundTypes' (a nil value)
Interface\AddOns\Capping\Capping.lua:288: in function `?'
Interface\AddOns\Capping\Capping.lua:56: in function <Interface\AddOns\Capping\Capping.lua:55>

Locals: self = <table> {
 AVTurnIn = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:618
 GetBar = <function> defined @Interface\AddOns\Capping\Capping.lua:464
 CheckTowerHealth = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:1114
 PLAYER_LOGIN = <function> defined @Interface\AddOns\Capping\Capping.lua:87
 AREA_POIS_UPDATED = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:153
 RestartSiegeBar = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:964
 StartBar = <function> defined @Interface\AddOns\Capping\Capping.lua:396
 ScorePredictor = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:281
 WGSync = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:1193
 L = <table> {
 }
 AVTurnInComplete = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:673
 AVTurnInProgress = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:663
 ZONE_CHANGED_NEW_AREA = <function> defined @Interface\AddOns\Capping\Capping.lua:162
 StopBar = <function> defined @Interface\AddOns\Capping\Capping.lua:445
 IoCSync = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:897
 START_TIMER = <function> defined @Interface\AddOns\Capping\Capping.lua:69
 AVSync = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:597
 CheckGateHealth = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:789
 RegisterEvent = <function> defined @Interface\AddOns\Capping\Capping.lua:62
 HealthUpdate = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:450
 AddBG = <function> defined @Interface\AddOns\Capping\Capping.lua:156
 UPDATE_BATTLEFIELD_STATUS = <function> defined @Interface\AddOns\Capping\Capping.lua:229
 Test = <function> defined @Interface\AddOns\Capping\Capping.lua:308
 UnregisterEvent = <function> defined @Interface\AddOns\Capping\Capping.lua:65
 RegisterTempEvent = <function> defined @Interface\AddOns\Capping\Capping.lua:58
}
queueId = 1
status = "queued"
map = "Alterac Valley"
_ = 0
_ = 0
_ = false
size = false
_ = "Eastern Kingdoms"
zoneType = "none"
esttime = 207.319000
waited = 315
estremain = -107.681000
bar = nil
icon = nil
(*temporary) = 1
(*temporary) = nil
(*temporary) = "attempt to call global 'GetNumBattlegroundTypes' (a nil value)"
GetBattlefieldStatus = <function> defined =[C]:-1
format = <function> defined =[C]:-1
ARENA = "Arena"
GetBattlefieldPortExpiration = <function> defined =[C]:-1
db = <table> {
 SetProfile = <function> defined @Interface\AddOns\Accountant_Classic\Libs\AceDB-3.0\AceDB-3.0.lua:430
 defaults = <table> {
 }
 callbacks = <table> {
 }
 RegisterDefaults = <function> defined @Interface\AddOns\Accountant_Classic\Libs\AceDB-3.0\AceDB-3.0.lua:398
 CopyProfile = <function> defined @Interface\AddOns\Accountant_Classic\Libs\AceDB-3.0\AceDB-3.0.lua:549
 ResetProfile = <function> defined @Interface\AddOns\Accountant_Classic\Libs\AceDB-3.0\AceDB-3.0.lua:584
 keys = <table> {
 }
 UnregisterAllCallbacks = <function> defined @Interface\AddOns\Accountant_Classic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 DeleteProfile = <function> defined @Interface\AddOns\Accountant_Classic\Libs\AceDB-3.0\AceDB-3.0.lua:510
 sv = <table> {
 }
 profile = <table> {
 }
 RegisterCallback = <function> defined @Interface\AddOns\Accountant_Classic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetNamespace = <function> defined @Interface\AddOns\Accountant_Classic\Libs\AceDB-3.0\AceDB-3.0.lua:676
 ResetDB = <function> defined @Interface\AddOns\Accountant_Classic\Libs\AceDB-3.0\AceDB-3.0.lua:612
 Unre`

**Comment by funkydude** [comment]
Thanks
