### ISSUE TITLE
Feature request: BG Start Timer (Classic)

### ISSUE THREAD

**Issue by heyiamsven** [BigWigsMods/Capping#50]
Is it possible to implement battleground start timers? Maybe the function could look in the chat for the "BG Starts in 30 seconds or 1minute" announcement and start a timer bar based on that message.

**Comment by Havenloft** [comment]
DBM - PvP Mod has this feature. I do think it would be nice to have in Capping as well.

**Comment by funkydude** [comment]
Fixed in BCC update.
