### ISSUE TITLE
TimeTrackel nil

### ISSUE THREAD

**Issue by WMage** [BigWigsMods/Capping#52]
classic version

Message: ..\AddOns\Capping\Capping.lua line 72:
   attempt to index global 'TimerTracker' (a nil value)
Debug:
   Capping\Capping.lua:72: ?()
   Capping\Capping.lua:56:
      Capping\Capping.lua:55

**Comment by Rippeee** [comment]
Currrent temporary fix   Replace ur Battleground lua with this.
https://github.com/Nomar111/Public.git

**Comment by funkydude** [comment]
Thanks
