### ISSUE TITLE
GetNumBattlegroundTypes nil

### ISSUE THREAD

**Issue by WMage** [BigWigsMods/Capping#53]
classic version

Message: ..\AddOns\Capping\Capping.lua line 275:
   attempt to call global 'GetNumBattlegroundTypes' (a nil value)
Debug:
   Capping\Capping.lua:275: ?()
   Capping\Capping.lua:56:
      Capping\Capping.lua:55

**Comment by Rippeee** [comment]
Same for me, it worked nice but suddenly after relog its giving me  2-3 different errors, and atm it seems that only thing that works  is Boss Health% bars,   none of the Gy's is showing

Message: ..\AddOns\Capping\battlegrounds.lua line 544:
   attempt to call upvalue 'GetScoreInfo' (a nil value)
Debug:
   [C]: ?
   Capping\battlegrounds.lua:544:
      Capping\battlegrounds.lua:542

**Comment by Rippeee** [comment]
Currrent temporary fix   Replace ur Battleground lua with this.
https://github.com/Nomar111/Public.git

**Comment by funkydude** [comment]
Thanks
