### ISSUE TITLE
classic version bugged

### ISSUE THREAD

**Issue by Lafoudre28** [BigWigsMods/Capping#54]
Message: Interface\AddOns\Capping\Capping.lua:275: attempt to call global 'GetNumBattlegroundTypes' (a nil value)
Time: Fri Dec 20 13:50:57 2019
Count: 1
Stack: Interface\AddOns\Capping\Capping.lua:275: attempt to call global 'GetNumBattlegroundTypes' (a nil value)
Interface\AddOns\Capping\Capping.lua:275: in function `?'
Interface\AddOns\Capping\Capping.lua:56: in function <Interface\AddOns\Capping\Capping.lua:55>

Locals: self = <table> {
 AVTurnIn = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:618
 GetBar = <function> defined @Interface\AddOns\Capping\Capping.lua:464
 CheckTowerHealth = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:1114
 PLAYER_LOGIN = <function> defined @Interface\AddOns\Capping\Capping.lua:87
 AREA_POIS_UPDATED = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:153
 RestartSiegeBar = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:964
 StartBar = <function> defined @Interface\AddOns\Capping\Capping.lua:396
 ScorePredictor = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:281
 WGSync = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:1193
 L = <table> {
 }
 AVTurnInComplete = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:673
 AVTurnInProgress = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:663
 ZONE_CHANGED_NEW_AREA = <function> defined @Interface\AddOns\Capping\Capping.lua:162
 StopBar = <function> defined @Interface\AddOns\Capping\Capping.lua:445
 IoCSync = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:897
 START_TIMER = <function> defined @Interface\AddOns\Capping\Capping.lua:69
 AVSync = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:597
 CheckGateHealth = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:789
 RegisterEvent = <function> defined @Interface\AddOns\Capping\Capping.lua:62
 HealthUpdate = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:450
 AddBG = <function> defined @Interface\AddOns\Capping\Capping.lua:156
 UPDATE_BATTLEFIELD_STATUS = <function> defined @Interface\AddOns\Capping\Capping.lua:229
 Test = <function> defined @Interface\AddOns\Capping\Capping.lua:308
 UnregisterEvent = <function> defined @Interface\AddOns\Capping\Capping.lua:65
 RegisterTempEvent = <function> defined @Interface\AddOns\Capping\Capping.lua:58
}
queueId = 1
status = "queued"
map = "Vallée d'Alterac"
_ = 0
_ = 0
_ = false
size = false
_ = "Royaumes de l'est"
zoneType = "none"
esttime = 11.272000
waited = 1
estremain = 10.272000
bar = nil
icon = nil
(*temporary) = 1
(*temporary) = nil
(*temporary) = "attempt to call global 'GetNumBattlegroundTypes' (a nil value)"
GetBattlefieldStatus = <function> defined =[C]:-1
format = <function> defined =[C]:-1
ARENA = "Arène"
GetBattlefieldPortExpiration = <function> defined =[C]:-1
db = <table> {
 SetProfile = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceDB\AceDB-3.0.lua:430
 defaults = <table> {
 }
 callbacks = <table> {
 }
 RegisterDefaults = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceDB\AceDB-3.0.lua:398
 CopyProfile = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceDB\AceDB-3.0.lua:549
 ResetProfile = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceDB\AceDB-3.0.lua:584
 keys = <table> {
 }
 UnregisterAllCallbacks = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 DeleteProfile = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceDB\AceDB-3.0.lua:510
 sv = <table> {
 }
 profile = <table> {
 }
 RegisterCallback = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetNamespace = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceDB\AceDB-3.0.lua:676
 ResetDB = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceDB\AceDB-3.0.lua:612
 UnregisterCallback = <function>

**Comment by Rippeee** [comment]
Currrent temporary fix   Replace ur Battleground lua with this.
https://github.com/Nomar111/Public.git

**Comment by Captainyamilo** [comment]
> Currrent temporary fix Replace ur Battleground lua with this.
> https://github.com/Nomar111/Public.git

Where is that file located? I couldn't find it anywhere.

**Comment by funkydude** [comment]
Thanks
