### ISSUE TITLE
Timers are off sync

### ISSUE THREAD

**Issue by Rippeee** [BigWigsMods/Capping#55]
Hi!

Timers on GY's are a bit off sync  i know its rng 297-308  and u are most likely using 297. Same as DBM does. So its like 19 times out of 20  off sync.  Its 4-5sec off

Could u change it to 304?  DBM did that too :)

**Comment by funkydude** [comment]
Cannot confirm this. Tested in patch 8.3, GY timers still seem fine. Closing.
