### ISSUE TITLE
can't hand in Ivus the Forest Lord quest

### ISSUE THREAD

**Issue by vioray** [BigWigsMods/Capping#57]
for the most part Capping is a great addon. however there's a quest in Korrak's Revenge that rewards 1.5k honour at level 120 for handing in one storm crystal. it's impossible to hand the quest in with this addon enabled though because the addon instead automatically hands the crystals in for the repeatable and has no options to disable this 'feature'
this is an extremely serious oversight that needs urgent correction

**Comment by funkydude** [comment]
No longer relevant as the event is over.
