### ISSUE TITLE
Addon throwing LUA's upon entering AV

### ISSUE THREAD

**Issue by volostyle** [BigWigsMods/Capping#58]
Whenever I enter the BG, I get the following LUA:

Message: Interface\AddOns\Capping\Capping.lua:275: attempt to call global 'GetNumBattlegroundTypes' (a nil value)
Time: Fri Dec 27 11:16:53 2019
Count: 1
Stack: Interface\AddOns\Capping\Capping.lua:275: attempt to call global 'GetNumBattlegroundTypes' (a nil value)
[C]: in function `GetNumBattlegroundTypes'
Interface\AddOns\Capping\Capping.lua:275: in function `?'
Interface\AddOns\Capping\Capping.lua:56: in function <Interface\AddOns\Capping\Capping.lua:55>

Locals: 

Message: Interface\AddOns\Capping\battlegrounds.lua:544: attempt to call upvalue 'GetScoreInfo' (a nil value)
Time: Fri Dec 27 11:17:28 2019
Count: 1
Stack: Interface\AddOns\Capping\battlegrounds.lua:544: attempt to call upvalue 'GetScoreInfo' (a nil value)
[C]: ?
Interface\AddOns\Capping\battlegrounds.lua:544: in function <Interface\AddOns\Capping\battlegrounds.lua:542>

Locals:

**Comment by turetafr** [comment]
Same here

**Comment by phzi** [comment]
For the latter issue, in your battlegrounds.lua, replace line 544 with 
local scoreTbl = false

On quick glance it appears the broken code is related to syncing data between clients. Fixes the error, and capping still works as expected (counters and everything work in my patched battlegrounds.lua).

**Comment by funkydude** [comment]
Thanks
