### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Felipy22** [BigWigsMods/Capping#59]
Date: 2019-12-29 12:20:24
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Capping\Capping.lua line 275:
   attempt to call global 'GetNumBattlegroundTypes' (a nil value)
Debug:
   Capping\Capping.lua:275: ?()
   Capping\Capping.lua:56:
      Capping\Capping.lua:55
Locals:
self = <table> {
 GetBar = <function> defined @Interface\AddOns\Capping\Capping.lua:464
 CheckTowerHealth = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:1114
 PLAYER_LOGIN = <function> defined @Interface\AddOns\Capping\Capping.lua:87
 AREA_POIS_UPDATED = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:153
 RestartSiegeBar = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:964
 StartBar = <function> defined @Interface\AddOns\Capping\Capping.lua:396
 ScorePredictor = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:281
 WGSync = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:1193
 L = <table> {
 }
 ZONE_CHANGED_NEW_AREA = <function> defined @Interface\AddOns\Capping\Capping.lua:162
 StopBar = <function> defined @Interface\AddOns\Capping\Capping.lua:445
 IoCSync = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:897
 START_TIMER = <function> defined @Interface\AddOns\Capping\Capping.lua:69
 AVSync = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:597
 CheckGateHealth = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:789
 RegisterEvent = <function> defined @Interface\AddOns\Capping\Capping.lua:62
 HealthUpdate = <function> defined @Interface\AddOns\Capping\battlegrounds.lua:450
 AddBG = <function> defined @Interface\AddOns\Capping\Capping.lua:156
 UPDATE_BATTLEFIELD_STATUS = <function> defined @Interface\AddOns\Capping\Capping.lua:229
 Test = <function> defined @Interface\AddOns\Capping\Capping.lua:308
 UnregisterEvent = <function> defined @Interface\AddOns\Capping\Capping.lua:65
 RegisterTempEvent = <function> defined @Interface\AddOns\Capping\Capping.lua:58
}
queueId = 1
status = "queued"
map = "Vale Alterac"
_ = 12
_ = 0
_ = false
size = false
_ = "Reinos do Leste"
zoneType = "none"
esttime = 7.137000
waited = 1
estremain = 6.137000
bar = nil
icon = nil
(*temporary) = 1
(*temporary) = nil
(*temporary) = "attempt to call global 'GetNumBattlegroundTypes' (a nil value)"
GetBattlefieldStatus = <function> defined =[C]:-1
format = <function> defined =[C]:-1
ARENA = "Arena"
GetBattlefieldPortExpiration = <function> defined =[C]:-1
db = <table> {
 SetProfile = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\AceDB-3.0\AceDB-3.0.lua:430
 defaults = <table> {
 }
 callbacks = <table> {
 }
 RegisterDefaults = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\AceDB-3.0\AceDB-3.0.lua:398
 CopyProfile = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\AceDB-3.0\AceDB-3.0.lua:549
 ResetProfile = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\AceDB-3.0\AceDB-3.0.lua:584
 keys = <table> {
 }
 UnregisterAllCallbacks = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 DeleteProfile = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\AceDB-3.0\AceDB-3.0.lua:510
 sv = <table> {
 }
 profile = <table> {
 }
 RegisterCallback = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetNamespace = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\AceDB-3.0\AceDB-3.0.lua:676
 ResetDB = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\AceDB-3.0\AceDB-3.0.lua:612
 UnregisterCallback = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 GetProfiles = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\AceDB-3.0\AceDB-3.0.lua:472
 profiles = <table> {
 }
 GetCurrentProfile = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\AceDB-3.0\AceDB-3.0.lua:503
 RegisterNamespace = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\AceDB-3.0\AceDB-3.0.lua:646
}
cleanupQueue = <function> defined @Interface\AddOns\Capping\Capping.lua:213
GetBattlefieldEstimatedWaitTime = <function> defined =[C]:-1
GetBattlefieldTimeWaited = <function> defined =[C]:-1

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.4.4
  AtlasLootClassicData, vv1.4.4
  AtlasLootClassicDungeonsAndRaids, vv1.4.4
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.27
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BiSTracker, v1.4 
  BrightleafNameplateClassColors, v1.0
  Capping, vv2-classic
  CharacterStatsClassic, v2.8.1
  ClassicCastbars, vv1.2.2
  ClassicCastbarsOptions, v
  ClassicThreatMeter, v1.10
  DBMCore, v1.13.25
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  FastGuildInvite, v59
  honorspy, v1.7.1
  Informant, v8.2.6374 (SwimmingSeadragon)
  Mapster, v1.8.5
  Questie, v5.4.1
  RealMobHealth, v2.17
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Spy, v1.0.20
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TomTom, vv11303-1.0.9
  VendorPrice, v1.3.0
  WeakAuras, v2.15.5
  WeaponSwingTimer, v4.1.0
  whoaUnitFramesClassic, v1.3.4
  BlizRuntimeLib_ptBR v1.13.3.11303 <none>
  (ck=5bf)

**Comment by funkydude** [comment]
Thanks
