### ISSUE TITLE
Announce timers into active chat channel

### ISSUE THREAD

**Issue by cexikitin** [BigWigsMods/Capping#6]
Pretty sure that's how dbm handles it, when you shift click a timer announce it to whatever channel you had active last.  Announcing timers into say chat is not useful in most cases.

**Comment by elvador** [comment]
BigWigs will automatically chooses where to report depending on your current raid/group situation.

It uses the following priority:
1. Instance chat, when you're in an instance group (LFG tool, LFR)
2. Raid chat, when you're in a raid
3. Party chat, when you're in a party
4. Say, when none of the above fits

https://github.com/BigWigsMods/BigWigs/blob/master/Plugins/Bars.lua#L1372


Does this not work for you?

**Comment by cexikitin** [comment]
Never thought to ctrl click, does it make sense to even announce to say in any case tho?

**Comment by funkydude** [comment]
Yes.

**Comment by cexikitin** [comment]
It seems strange to me for the shift click behavior to be different from both dbm and bigwigs normal actions. If anything were to announce to say wouldn't it make more sense for it to be the ctrl click instead of shift click?

**Comment by funkydude** [comment]
You don't need to use a modifier with BigWigs. But if you do, the default is Ctrl, which is the same as Capping.
