### ISSUE TITLE
error joining BGs - classic

### ISSUE THREAD

**Issue by rump** [BigWigsMods/Capping#61]
Date: 2020-01-10 17:14:49
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Capping\Capping.lua line 275:
   attempt to call global 'GetNumBattlegroundTypes' (a nil value)
Debug:
   [C]: GetNumBattlegroundTypes()
   Capping\Capping.lua:275: ?()
   Capping\Capping.lua:56:
      Capping\Capping.lua:55

**Comment by funkydude** [comment]
Thanks
