### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by 720720** [BigWigsMods/Capping#65]
capping v4 classic

```
Message: Interface\AddOns\Capping\Modules\AlteracValley.lua:89: attempt to call upvalue 'GetScoreInfo' (a nil value)
Time: Thu Jan 16 11:39:45 2020
Count: 2
Stack: Interface\AddOns\Capping\Modules\AlteracValley.lua:89: attempt to call upvalue 'GetScoreInfo' (a nil value)
[C]: ?
Interface\AddOns\Capping\Modules\AlteracValley.lua:89: in function <Interface\AddOns\Capping\Modules\AlteracValley.lua:87>

Locals: 
```

**Comment by mcd8604** [comment]
Also got this:
Date: 2020-01-20 12:53:16
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Capping\Modules\AlteracValley.lua line 89:
   attempt to call upvalue 'GetScoreInfo' (a nil value)
Debug:
   Capping\Modules\AlteracValley.lua:89:
      Capping\Modules\AlteracValley.lua:87
Locals:
(for index) = 1
(for limit) = 80
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to call upvalue 'GetScoreInfo' (a nil value)"
GetScoreInfo = nil
hereFromTheStart = true
hasData = true
mod = <table> {
 GetBar = <function> defined @Interface\AddOns\Capping\Core.lua:175
 StartScoreEstimator = <function> defined @Interface\AddOns\Capping\Core.lua:459
 ExitZone = <function> defined @Interface\AddOns\Capping\Modules\AlteracValley.lua:184
 RestoreFlagCaptures = <function> defined @Interface\AddOns\Capping\Core.lua:665
 StartBar = <function> defined @Interface\AddOns\Capping\Core.lua:101
 GOSSIP_SHOW = <function> defined @Interface\AddOns\Capping\Modules\AlteracValley.lua:12
 StopScoreEstimator = <function> defined @Interface\AddOns\Capping\Core.lua:469
 CHAT_MSG_ADDON = <function> defined @Interface\AddOns\Capping\Modules\AlteracValley.lua:143
 EnterZone = <function> defined @Interface\AddOns\Capping\Modules\AlteracValley.lua:165
 StopBar = <function> defined @Interface\AddOns\Capping\Core.lua:150
 QUEST_COMPLETE = <function> defined @Interface\AddOns\Capping\Modules\AlteracValley.lua:75
 QUEST_PROGRESS = <function> defined @Interface\AddOns\Capping\Modules\AlteracValley.lua:61
 SetupHealthCheck = <function> defined @Interface\AddOns\Capping\Core.lua:353
 RegisterEvent = <function> defined @Interface\AddOns\Capping\Core.lua:195
 StopFlagCaptures = <function> defined @Interface\AddOns\Capping\Core.lua:661
 RegisterZone = <function> defined @Interface\AddOns\Capping\Core.lua:210
 StartFlagCaptures = <function> defined @Interface\AddOns\Capping\Core.lua:619
 StopAllBars = <function> defined @Interface\AddOns\Capping\Core.lua:169
 Timer = <function> defined @Interface\AddOns\Capping\Core.lua:215
 UnregisterEvent = <function> defined @Interface\AddOns\Capping\Core.lua:200
 StopHealthCheck = <function> defined @Interface\AddOns\Capping\Core.lua:364
}
allow = <function> defined @Interface\AddOns\Capping\Modules\AlteracValley.lua:83
stopTimer = nil
NewTicker = <function> defined @Interface\SharedXML\C_TimerAugment.lua:11
stop = <function> defined @Interface\AddOns\Capping\Modules\AlteracValley.lua:84
SendAddonMessage = <function> defined =[C]:-1

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.3
  Atlas, vv1.47.00.11303.00
  AtlasClassicWoW, vv1.47.00.11303.00
  AtlasLootClassic, vv1.4.5
  AtlasLootClassicData, vv1.4.5
  AtlasLootClassicDungeonsAndRaids, vv1.4.5
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Capping, vv4-classic
  CharacterStatsClassic, v3.1
  ClassicAuraDurations, v
  ClassicCastbars, vv1.2.3
  ClassicCastbarsOptions, v
  CTBarMod, v8.2.5.5
  CTBottomBar, v8.2.5.7
  CTBuffMod, v8.2.5.5
  CTCore, v8.2.5.6
  CTExpenseHistory, v8.2.5.6
  CTLibrary, v8.2.5.7
  DBMCore, v1.13.30
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  GatherMate2, v1.45.5
  GuildRosterManager, v1.831
  HonorAssist, v0.9.2
  HonorSpy, v1.8.4
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LeatrixMaps, v1.13.44
  LeatrixPlus, v1.13.45
  NugEnergy, v1.13.12
  OmniBar, vv10.7
  OmniCC, v8.3.1
  OPie, vAncient Walnut 6
  Quartz, v3.5-classic-5
  Questie, v5.5.1
  SheepMonitor, v1.22
  Spy, v1.0.21
  Stubby, v8.2.6376 (SwimmingSeadragon)
  WeakAuras, v2.16.1
  ZPerl, v5.9.0
  ZPerlArcaneBar, v
  ZPerlCustomHighlight, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=6ea)

**Comment by funkydude** [comment]
This should only happen once when you enter the zone. I'll look into it.

**Comment by funkydude** [comment]
Please join AV, open up the scoreboard then type this in chat:
```/dump GetBattlefieldScore(1)```

It would be best if you did it about 10 minutes in when everyone has a score that isn't 0, but that's not important.
Take a screenshot of the whole thing including the scoreboard and attach it here.

**Comment by shkabo** [comment]
At the start of BG for me
```[23:16:36] [1]="Alu-Bloodfang",
[23:16:36] [2]=0,
[23:16:36] [3]=0,
[23:16:36] [4]=0,
[23:16:36] [5]=0,
[23:16:36] [6]=0,
[23:16:36] [7]=13,
[23:16:36] [8]="Troll",
[23:16:36] [9]="Warrior",
[23:16:36] [10]="WARRIOR"```
later a bit in game when people got some score
```
[23:23:45] Dump: value=GetBattlefieldScore(1)
[23:23:45] [1]="Schamalani-Razorfen",
[23:23:45] [2]=6,
[23:23:45] [3]=25,
[23:23:45] [4]=1,
[23:23:45] [5]=594,
[23:23:45] [6]=0,
[23:23:45] [7]=8,
[23:23:45] [8]="Tauren",
[23:23:45] [9]="Shaman",
[23:23:45] [10]="SHAMAN"
```

**Comment by funkydude** [comment]
Fixed in BCC update.
