### ISSUE TITLE
Info: what does this mean?

### ISSUE THREAD

**Issue by c0mm0n** [BigWigsMods/Capping#66]
<img width="346" alt="image" src="https://user-images.githubusercontent.com/1181493/72661994-7addc300-39e1-11ea-8834-3fcf5ca97e1d.png">

Ty

**Comment by funkydude** [comment]
This seems to indicate that the server sends a "battle begins" timer bar, but it is just ignored by the client since the 2 minute "battle begins" timer bar was removed in classic.
