### ISSUE TITLE
Östlicher Frostwolfturm / Eastern Frostwolf Tower

### ISSUE THREAD

**Issue by fnordson** [BigWigsMods/Capping#68]
There is an issue which is probably related to the translation or usage of the umlaut "Ö". 
The timer for the Eastern Frostwolf Tower in AV does not work properly. It's been triggered so the timer starts but it doesn't get the message when the tower has been recapped. 
I assume it's due to the Ö in the German message. 

Also: is there a way to change it to english even if I have a German client? 
I ask because the general AV/BG language has become english and posting timers into chat may cause confusion.

**Comment by funkydude** [comment]
> There is an issue which is probably related to the translation or usage of the umlaut "Ö".

It doesn't matter what the tower is called or what language it is in.
Perhaps you can provide some screenshot evidence of this.

> Also: is there a way to change it to english even if I have a German client?

No. It uses what the game tells it to use.

**Comment by fnordson** [comment]
My guess regarding the name came from the fact that the PvP plug-in for DBM had the same problem and there is an issue with missing letters. 
I'll deliver some screenshots tomorrow.

**Comment by fnordson** [comment]
![Ostlich](https://user-images.githubusercontent.com/5624605/74267792-0a3b7500-4d07-11ea-9a84-dbe7cd0a644f.jpg)

Unfortunately whenever Ally got the east tower, they were already winning and didn't lose it so I wasn't able to get a screenshot for the timer running past the announcement. 
However here is already a screenshot showing the problem with the capital Ö (being displayed here as: ?)

**Comment by funkydude** [comment]
Honestly I'm not really sure how to address this as I'm assuming this is actually broken in the Blizzard client.

Can you take a screenshot of the actual map tooltip? Hovering over the tower on your world map should show the name, and I assume will also contain this question mark after the alliance assault it? If it doesn't then I'm going to need to write you some debug to run.

**Comment by fnordson** [comment]
Here you go: 

![map_ofw](https://user-images.githubusercontent.com/5624605/76164019-88930780-614b-11ea-8469-12859a8fe57c.jpg)

**Comment by funkydude** [comment]
No, whilst it's under attack :)

**Comment by fnordson** [comment]
Here it is: 
![ostlu](https://user-images.githubusercontent.com/5624605/76246959-0257ed80-623f-11ea-89a3-5a69c2cc9274.jpg)

**Comment by fnordson** [comment]
Related(?) issue for Arathi:

Stables:
![stabl](https://user-images.githubusercontent.com/5624605/76707025-35412c00-66ec-11ea-975c-0e9cdbb3925e.jpg)
![stabl2](https://user-images.githubusercontent.com/5624605/76707028-36725900-66ec-11ea-88db-d91044918d90.jpg)

Lumber Mill:
![sw2](https://user-images.githubusercontent.com/5624605/76707026-35d9c280-66ec-11ea-97f6-b6a35e4c25e3.jpg)
![sw1](https://user-images.githubusercontent.com/5624605/76707027-35d9c280-66ec-11ea-9b93-8c02382ffb4c.jpg)

**Comment by funkydude** [comment]
Is this still an issue?

**Comment by funkydude** [comment]
No response, and no one else indicating they also have the issue, closing.
