### ISSUE TITLE
[Classic] Arathi Basin Final Score Estimation

### ISSUE THREAD

**Issue by addohm** [BigWigsMods/Capping#70]
It doesn't seem to work at all.  Doesn't even show up.

**Comment by TheLiquidCat** [comment]
Same issue for Classic version.

**Comment by funkydude** [comment]
I'm going to assume you are both talking about classic as this doesn't appear to be an issue on live.

**Comment by funkydude** [comment]
No one showed interest in helping resolve this, closing.
