### ISSUE TITLE
AV Module Error

### ISSUE THREAD

**Issue by orionshock** [BigWigsMods/Capping#72]
Message: ..\AddOns\Capping\Modules\AlteracValley.lua line 89:
   attempt to call upvalue 'GetScoreInfo' (a nil value)
Debug:
   [C]: ?
   Capping\Modules\AlteracValley.lua:89:
      Capping\Modules\AlteracValley.lua:87

Version off of curseforge: v4-classic, Jan 15, 2020

**Comment by audiosmith** [comment]
Same here

**Comment by audiosmith** [comment]
1x Capping\Modules\AlteracValley.lua:89: attempt to call upvalue 'GetScoreInfo' (a nil value)
Capping\Modules\AlteracValley.lua:89: in function <Capping\Modules\AlteracValley.lua:87>

Locals:
(for index) = 1
(for limit) = 80
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to call upvalue 'GetScoreInfo' (a nil value)"
GetScoreInfo = nil
hereFromTheStart = true
hasData = true
mod = <table> {
 GetBar = <function> defined @Capping\Core.lua:175
 StartScoreEstimator = <function> defined @Capping\Core.lua:459
 ExitZone = <function> defined @Capping\Modules\AlteracValley.lua:184
 RestoreFlagCaptures = <function> defined @Capping\Core.lua:665
 StartBar = <function> defined @Capping\Core.lua:101
 GOSSIP_SHOW = <function> defined @Capping\Modules\AlteracValley.lua:12
 StopScoreEstimator = <function> defined @Capping\Core.lua:469
 CHAT_MSG_ADDON = <function> defined @Capping\Modules\AlteracValley.lua:143
 EnterZone = <function> defined @Capping\Modules\AlteracValley.lua:165
 StopBar = <function> defined @Capping\Core.lua:150
 QUEST_COMPLETE = <function> defined @Capping\Modules\AlteracValley.lua:75
 QUEST_PROGRESS = <function> defined @Capping\Modules\AlteracValley.lua:61
 SetupHealthCheck = <function> defined @Capping\Core.lua:353
 RegisterEvent = <function> defined @Capping\Core.lua:195
 StopFlagCaptures = <function> defined @Capping\Core.lua:661
 RegisterZone = <function> defined @Capping\Core.lua:210
 StartFlagCaptures = <function> defined @Capping\Core.lua:619
 StopAllBars = <function> defined @Capping\Core.lua:169
 Timer = <function> defined @Capping\Core.lua:215
 UnregisterEvent = <function> defined @Capping\Core.lua:200
 StopHealthCheck = <function> defined @Capping\Core.lua:364
}
allow = <function> defined @Capping\Modules\AlteracValley.lua:83
stopTimer = nil
NewTicker = <function> defined @SharedXML\C_TimerAugment.lua:11
stop = <function> defined @Capping\Modules\AlteracValley.lua:84
SendAddonMessage = <function> defined =[C]:-1

**Comment by shkabo** [comment]
Already posted in #65

**Comment by Kataclasm** [comment]
Still not fixed.

5x Capping\Modules\AlteracValley.lua:89: attempt to call upvalue 'GetScoreInfo' (a nil value)
Capping\Modules\AlteracValley.lua:89: in function <Capping\Modules\AlteracValley.lua:87>

Locals:
(for index) = 1
(for limit) = 80
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to call upvalue 'GetScoreInfo' (a nil value)"
GetScoreInfo = nil
hereFromTheStart = true
hasData = true
mod = <table> {
 GetBar = <function> defined @Capping\Core.lua:175
 StartScoreEstimator = <function> defined @Capping\Core.lua:459
 ExitZone = <function> defined @Capping\Modules\AlteracValley.lua:184
 RestoreFlagCaptures = <function> defined @Capping\Core.lua:665
 StartBar = <function> defined @Capping\Core.lua:101
 GOSSIP_SHOW = <function> defined @Capping\Modules\AlteracValley.lua:12
 StopScoreEstimator = <function> defined @Capping\Core.lua:469
 CHAT_MSG_ADDON = <function> defined @Capping\Modules\AlteracValley.lua:143
 EnterZone = <function> defined @Capping\Modules\AlteracValley.lua:165
 StopBar = <function> defined @Capping\Core.lua:150
 QUEST_COMPLETE = <function> defined @Capping\Modules\AlteracValley.lua:75
 QUEST_PROGRESS = <function> defined @Capping\Modules\AlteracValley.lua:61
 SetupHealthCheck = <function> defined @Capping\Core.lua:353
 RegisterEvent = <function> defined @Capping\Core.lua:195
 StopFlagCaptures = <function> defined @Capping\Core.lua:661
 RegisterZone = <function> defined @Capping\Core.lua:210
 StartFlagCaptures = <function> defined @Capping\Core.lua:619
 StopAllBars = <function> defined @Capping\Core.lua:169
 Timer = <function> defined @Capping\Core.lua:215
 UnregisterEvent = <function> defined @Capping\Core.lua:200
 StopHealthCheck = <function> defined @Capping\Core.lua:364
}
allow = <function> defined @Capping\Modules\AlteracValley.lua:83
stopTimer = nil
NewTicker = <function> defined @SharedXML\C_TimerAugment.lua:11
stop = <function> defined @Capping\Modules\AlteracValley.lua:84
SendAddonMessage = <function> defined =[C]:-1
