### ISSUE TITLE
LUA mistake when entrance in a BG

### ISSUE THREAD

**Issue by Lafoudre28** [BigWigsMods/Capping#74]
Message: Interface\AddOns\Capping\Modules\AlteracValley.lua:89: attempt to call upvalue 'GetScoreInfo' (a nil value)
Time: Sun May 10 10:25:08 2020
Count: 1
Stack: Interface\AddOns\Capping\Modules\AlteracValley.lua:89: attempt to call upvalue 'GetScoreInfo' (a nil value)

Locals:

**Comment by CodeSpartan** [comment]
Same error for me immediately after entering AV.

**Comment by funkydude** [comment]
Fixed for BCC.
