### ISSUE TITLE
Tower Cap bars

### ISSUE THREAD

**Issue by stamicvs** [BigWigsMods/Capping#75]
Hi funkehdude,

I wondered if I am currently missing something or it is not availyble in capping.
Is there a bar available to see the cap-status of a tower e.g. in Eye of the Storm which can replace the default bar?
The default timers are pretty difficult to see and I would like to have them in capping also.
The default frame is called WorldStateCaptureBar1 (Flag Capture Timer Bar in MoveAnything)
If this is not already implemented do you see a chance for an implementation?

Thank you very much in advance.

**Comment by funkydude** [comment]
I think you're talking about the little progress bar that (by default) appears under the minimap location?

If so, are you requesting that a Capping bar is created to mimic this bar?

**Comment by funkydude** [comment]
No response, closing.
