### ISSUE TITLE
Capping Battlegrounds

### ISSUE THREAD

**Issue by dragonrlm** [BigWigsMods/Capping#77]
Date: 2020-05-26 15:35:38
ID: 1
Error occured in: Global
Count: 1
Message: Invalid Custom Control Type - LQDropdown
Debug:
   ...gECS-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1621: FeedGroup()
   ...gECS-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1546:
      ...gECS-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1526
   [C]: ?
   ...\AddOns\honorspy\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua:72:
      ...\AddOns\honorspy\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua:70
   ...\AddOns\honorspy\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua:287: Fire()
   ...Libs\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua:156: SelectTab()
   ...gECS-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1657: FeedGroup()
   ...gECS-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1901: Open()
   ...Ons\ExtendedCharacterStats\Modules\Config\Config.lua:32: CreateWindow()
   ...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:84: CreateWindow()
   ExtendedCharacterStats\ECS.lua:67:
      ExtendedCharacterStats\ECS.lua:65
   ExtendedCharacterStats\ECS.lua:35:
      ExtendedCharacterStats\ECS.lua:28
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ACP, v3.5.7 
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicData, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  AVQ, v28
  Capping, vv4-classic
  Coordinates, v2.1.0
  Details, v
  DetailsTinyThreat, v
  EasyMail, v4.3.2
  ExtendedCharacterStats, v2.4.0
  HKCounter, v4.4
  honorspy, v1.7.3
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TomTom, vv11304-1.1.2
  WeaponSwingTimer, v4.1.0
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=205)

**Comment by funkydude** [comment]
Not related to Capping.
