### ISSUE TITLE
deDE locale Error message fix

### ISSUE THREAD

**Issue by sp0cki18** [BigWigsMods/Capping#82]
Hey,
in core.lua (Capping) I added "and x ~= "deDE" in line 728 - otherwise it throws an errormessage, that deDE locale cant be detected at the start of the game.

```
self:Timer(15, function()
			local x = GetLocale()
			if x ~= "enUS" and x ~= "enGB" and x ~= "zhCN" and x ~= "ruRU" **and x ~= "deDE"** then -- XXX temp
				print("|cFF33FF99Capping|r is missing locale for", x, "and needs your help! Please visit the project page on GitHub for more info.")
```

**Comment by Triplehxh** [comment]
I also updated the deDE locale file to have a entries translated

**Comment by funkydude** [comment]
> 
> 
> I also updated the deDE locale file to have a entries translated

Where is this updated? I have not seen a pull request from you.

The message will remain until someone translates the addon.

**Comment by Triplehxh** [comment]
> > I also updated the deDE locale file to have a entries translated
> 
> Where is this updated? I have not seen a pull request from you.
> 
> The message will remain until someone translates the addon.

I edited the Options/Locales/deDE.lua and used this "Propose changes" function from GitHub. 
If you will not find my changes I will Crosscheck also the normal Locales/deDE.lua on the first view it looks already translated.

And i will attach the both files here

**Comment by funkydude** [comment]
No response in the PR that was provided, closing.

**Comment by Fluke667** [comment]
![WoWScrnShot_091522_014757](https://user-images.githubusercontent.com/20209642/190282089-d4dc9fc4-e96b-4dc7-b9b1-39239124cbac.jpg)

**Comment by funkydude** [comment]
@Fluke667 That's working as intended. No one has provided functional German translations.

**Comment by Fluke667** [comment]
> @Fluke667 That's working as intended. No one has provided functional German translations.

deDE.lua not working?
