### ISSUE TITLE
zhTW update

### ISSUE THREAD

**Issue by CrisReus** [BigWigsMods/Capping#86]
translate by Dololo@miliui
arrange by CrisReus@CN主宰之剑
`
if GetLocale() ~= "zhTW" then return end
local _, mod = ...
local L = mod.L

L.battleBegins = "開始"
L.finalScore = "估計最終比數: %d - %d"
L.flagRespawns = "旗幟已重置"

L.takenTheFlagTrigger = "^(.+)已經奪走了旗幟!"
L.hasTakenTheTrigger = "奪取了"
L.upgradeToTrigger = "升級成"
L.droppedTrigger = "丟掉了"
L.capturedTheTrigger = "佔據了"

L.hordeGate = "部落大門"
L.allianceGate = "聯盟大門"
L.gatePosition = "%s (%s)"
L.west = "西"
L.front = "前"
L.east = "東"
L.hordeBoss = "部落首領"
L.allianceBoss = "聯盟首領"
L.galvangar = "加爾凡加上尉"
L.balinda = "巴琳達"
--L.ivus = "Ivus"
--L.lokholar = "Lokholar"
L.handIn = "|cFF33FF99Capping|r: 自動處理任務物品。"

--- Alliance IoC Workshop yells:
-- Gnomish Mechanic yells: I'm halfway there! Keep the Horde away from here.  They don't teach fighting in engineering school!
-- Gnomish Mechanic yells: It's broken already?! No worries. It's nothing I can't fix.
--- Horde IoC Workshop yells:
-- Goblin Mechanic yells: I'm about halfway done! Keep the Alliance away - fighting's not in my contract!
-- Goblin Mechanic yells: It's broken again?! I'll fix it... just don't expect the warranty to cover this.
L.halfway = "完成一半"
L.broken = "損壞"

-- Wintergrasp 冬握湖戰鬥
L.damaged = "|cFF33FF99Capping|r: %s 損傷"
L.destroyed = "|cFF33FF99Capping|r: %s 摧毀"
L.northEastKeep = "東北要塞塔"
L.southEastKeep = "東南要塞塔"
L.northWestKeep = "西北要塞塔"
L.southWestKeep = "西南要塞塔"
L.northWest = "西北側牆"
L.southWest = "西南側牆"
L.south = "南側牆"
L.southEast = "東南側牆"
L.northEast = "東北側牆"
L.innerWest = "西內側牆"
L.innerSouth = "南內側牆"
L.innerEast = "東內側牆"
L.southGate = "南側大門"
L.mainEntrance = "主要入口"
L.westTower = "西側塔"
L.southTower = "南側塔"
L.eastTower = "東側塔"
`
Options
`
if GetLocale() ~= "zhTW" then return end
local _, mod = ...
local L = mod.L

-- Options
L.general = "一般"
L.test = "測試"
L.lock = "鎖定位置"
L.barIcon = "顯示圖示"
L.showTime = "顯示時間"
L.fillBar = "反向填色"
L.font = "字型"
L.fontSize = "文字大小"
L.monochrome = "無消除鋸齒文字"
L.outline = "外框"
L.none = "無"
L.thin = "細"
L.thick = "粗"
L.texture = "材質"
L.barSpacing = "條列間距"
L.barWidth = "條列寬度"
L.barHeight = "條列高度"
L.alignText = "文字對齊"
L.alignTime = "時間對齊"
L.alignIcon = "圖示對齊"
L.left = "左"
L.center = "中"
L.right = "右"
L.growUpwards = "往上增長"
L.textColor = "文字顏色"
L.allianceBars = "聯盟條列"
L.hordeBars = "部落條列"
L.queueBars = "隊伍佇列條列"
L.otherBars = "其他條列"
L.barBackground = "條列背景"

-- Features
L.features = "功能"
L.queueBarsDesc = "啟用條列來顯示你所加入的隊伍佇列，以及在隊伍佇列中的估計時間。"
L.barClickDesc = "設定點擊條列時的組合按鍵，以輸出到指定聊天頻道。三個全部設為 '無' 時會停用點擊條列的功能，讓你可以穿透點擊到條列後面的東西。"
L.shiftClick = "Shift-左鍵"
L.controlClick = "Ctrl-左鍵"
L.altClick = "Alt-左鍵"
L.sayChat = "說話頻道"
L.raidChat = "隊伍頻道"
L.clickableBars = "點擊條列"
L.loudQueue = "大聲音效"
L.loudQueueDesc = "隊伍佇列準備完成時，會強制使用 '主音量' 聲道來播放通知音效。"
`

**Comment by funkydude** [comment]
@CrisReus Thank you!

    --- Alliance IoC Workshop yells:
    -- Gnomish Mechanic yells: I'm halfway there! Keep the Horde away from here. They don't teach fighting in engineering school!
    -- Gnomish Mechanic yells: It's broken already?! No worries. It's nothing I can't fix.

    --- Horde IoC Workshop yells:
    -- Goblin Mechanic yells: I'm about halfway done! Keep the Alliance away - fighting's not in my contract!
    -- Goblin Mechanic yells: It's broken again?! I'll fix it... just don't expect the warranty to cover this.

I need these translated exactly as they appear in-game.

That means you need to go into the IoC battle and copy paste the yells. If they are not exactly the same, it won't work.

**Comment by CrisReus** [comment]
I tried to get this information from IoC, but I couldn't get it. 

Or I don't know how to trigger this information.

**Comment by funkydude** [comment]
@CrisReus I will explain:
When you join IoC, you can capture the middle area (workshop) by capturing the flag.
If the Horde capture it, the "Goblin Mechanic" will appear.
If the Alliance capture it, the "Gnomish Mechanic" will appear.

They both function the same but have different yells.
The "halfway" yell will happen after about 90 seconds after capturing it.
After the siege engine has finished building, someone can enter it and control it. When it is destroyed, the "it's broken" yell will happen.

To see both yells you need to be in range of them, so you need to be close to the middle of the map. If you are not close you will not see the yells.
It doesn't matter if you are Alliance or Horde, it matters who captures the flag. So if you are Horde you can still see the Alliance/Gnomish yells by letting alliance capture the middle.

Thanks!

**Comment by CrisReus** [comment]
I will try.
But why do I see other localization files comment out this paragraph.

**Comment by funkydude** [comment]
@CrisReus The comment is for us to have a reference.
So when we decide what `L.halfway` & `L.broken` is we know it will work for both Horde & Alliance, because we can then see the full yell in the comment to verify it.

**Comment by funkydude** [comment]
No response, closing.
