### ISSUE TITLE
kor update

### ISSUE THREAD

**Issue by fallendos** [BigWigsMods/Capping#87]
if GetLocale() ~= "koKR" then return end
local _, mod = ...
local L = mod.L

L.battleBegins = "전투 개시"
L.finalScore = "종료: %d - %d"
L.flagRespawns = "깃발 생성"

L.takenTheFlagTrigger = "^(.+)|1이;가; 깃발을 차지했습니다!"
L.hasTakenTheTrigger = "점령했습니다"
L.upgradeToTrigger = "추가 전리품"
L.droppedTrigger = "([^ ]*)|1이;가; ([^!]*) 깃발을 떨어뜨렸습니다!"
L.capturedTheTrigger = "([^ ]*)|1이;가; ([^!]*) 깃발 쟁탈에 성공했습니다!"

L.hordeGate = "호드 성문"
L.allianceGate = "얼라이언스 성문"
L.gatePosition = "%s (%s)"
L.west = "서문"
L.front = "정문"
L.east = "동문"
L.hordeBoss = "호드 대장"
L.allianceBoss = "얼라이언스 대장"
L.galvangar = "갈반가르"
L.balinda = "발린다"
L.ivus = "이부스"
L.lokholar = "로크홀라"
L.handIn = "|cFF33FF99Capping|r: 자동으로 퀘스트 아이템을 전달합니다."

--- Alliance IoC Workshop yells:
-- Gnomish Mechanic yells: I'm halfway there! Keep the Horde away from here.  They don't teach fighting in engineering school!
-- Gnomish Mechanic yells: It's broken already?! No worries. It's nothing I can't fix.
--- Horde IoC Workshop yells:
-- Goblin Mechanic yells: I'm about halfway done! Keep the Alliance away - fighting's not in my contract!
-- Goblin Mechanic yells: It's broken again?! I'll fix it... just don't expect the warranty to cover this.
L.halfway = "절반"
L.broken = "파괴됨"

-- Wintergrasp(겨울손아귀 호수)
L.damaged = "|cFF33FF99Capping|r: %s 피해를 받았습니다."
L.destroyed = "|cFF33FF99Capping|r: %s 파괴 되었습니다."
L.northEastKeep = "북동 경비탑"
L.southEastKeep = "남동 경비탑"
L.northWestKeep = "북서 경비탑"
L.southWestKeep = "남서 경비탑"
L.northWest = "북서쪽 성벽"
L.southWest = "남서쪽 성벽"
L.south = "남쪽 성벽"
L.southEast = "남동쪽 성벽"
L.northEast = "북서쪽 성벽"
L.innerWest = "서쪽 내성벽"
L.innerSouth = "남쪽 내성벽"
L.innerEast = "동쪽 내성벽"
L.southGate = "남쪽 성문"
L.mainEntrance = "정문"
L.westTower = "서쪽 경비탑"
L.southTower = "남쪽 경비탑"
L.eastTower = "동쪽 경비탑"

**Comment by funkydude** [comment]
@fallendos Thank you!

> --- Alliance IoC Workshop yells:
> -- Gnomish Mechanic yells: I'm halfway there! Keep the Horde away from here. They don't teach fighting in engineering school!
> -- Gnomish Mechanic yells: It's broken already?! No worries. It's nothing I can't fix.

> --- Horde IoC Workshop yells:
> -- Goblin Mechanic yells: I'm about halfway done! Keep the Alliance away - fighting's not in my contract!
> -- Goblin Mechanic yells: It's broken again?! I'll fix it... just don't expect the warranty to cover this.

I need these translated **exactly** as they appear in-game.

That means you need to go into the IoC battle and copy paste the yells. If they are not exactly the same, it won't work.

**Comment by funkydude** [comment]
@fallendos I will explain how you can see these yells:

When you join IoC, you can capture the middle area (workshop) by capturing the flag.
If the Horde capture it, the "Goblin Mechanic" will appear.
If the Alliance capture it, the "Gnomish Mechanic" will appear.

They both function the same but have different yells.
The "halfway" yell will happen after about 90 seconds after capturing it.
After the siege engine has finished building, someone can enter it and control it. When it is destroyed, the "it's broken" yell will happen.

To see both yells you need to be in range of them, so you need to be close to the middle of the map. If you are not close you will not see the yells.
It doesn't matter if you are Alliance or Horde, it matters who captures the flag. So if you are Horde you can still see the Alliance/Gnomish yells by letting alliance capture the middle.

Thanks!

**Comment by funkydude** [comment]
No response, closing
