### ISSUE TITLE
IoC wall HP and reported HP from capping not same.

### ISSUE THREAD

**Issue by MHketbi** [BigWigsMods/Capping#97]
## Describe the problem
actuall wall health and capping health bar are not in sync

### What steps will reproduce the problem?

1.  joined IoC and noticed it, nothing special was done.
 

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![Wow_14032021_002522](https://user-images.githubusercontent.com/2147851/111043493-5140f000-845c-11eb-9970-3c938674c997.png)

### What version of the addon are you using? (Stating 'latest' is not useful)
9.0.12

### Do you have an error log of what happened?
not an addon breaking issue

**Comment by funkydude** [comment]
Thanks!
